fix bump version

diff --git a/.github/workflows/bump_version.yml b/.github/workflows/bump_version.yml
--- a/.github/workflows/bump_version.yml
+++ b/.github/workflows/bump_version.yml
@@ -110,7 +110,7 @@ jobs:
 
             - name: Bump version
               run: |
-                set -euo pipefail # stop on errors, print commands, fail on pipe fails
+                set -euox pipefail # stop on errors, print commands, fail on pipe fails
 
                 # set the author in git
                 git config user.name "prosoponator[bot]"
@@ -121,7 +121,7 @@ jobs:
                 git checkout ${{ github.event.inputs.src }}
 
                 # check the source branch (e.g. staging) is up-to-date with the dest branch (e.g. main)
-                if [ "$(git rev-list --count HEAD..origin/${{ github.event.inputs.dest }})" -ne 0 ]; then
+                if [ "$(git rev-list --count HEAD..origin/${{ github.event.inputs.dest }})" -ne "0" ]; then
                     echo "Source branch ${{ github.event.inputs.src }} is not up-to-date with destination branch ${{ github.event.inputs.dest }}. PR destination branch into the source branch and try again."
                     exit 1
                 fi
