Update bump_version.yml

diff --git a/.github/workflows/bump_version.yml b/.github/workflows/bump_version.yml
--- a/.github/workflows/bump_version.yml
+++ b/.github/workflows/bump_version.yml
@@ -78,7 +78,7 @@ jobs:
 
             - name: Bump version
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                set -euo pipefail # stop on errors, print commands, fail on pipe fails
 
                 # set the author in git
                 git config user.name "prosoponator[bot]"
@@ -97,17 +97,24 @@ jobs:
                 pkgJsons=$(npm run --silent ws:pkg)
                 pkgNames=$(npm run --silent ws:ls)
                 for pkgJson in $pkgJsons; do
+                    echo "Bumping version in $pkgJson"
                     # for each package in the workspace, set the version number
-                    cat $pkgJson | jq ".version = \"${{ github.event.inputs.version }}\"" > $pkgJson
+                    cat $pkgJson | jq ".version = \"${{ github.event.inputs.version }}\"" > tmp
+                    mv tmp $pkgJson
                     for pkgName in $pkgNames; do
                         # for each package in the workspace, check whether it is in the dependencies of the current package
                         # if so, bump the version number in the dependencies
-                        cat $pkgJson | jq "if .dependencies[\"$pkgName\"] then .dependencies[\"$pkgName\"] = \"^${{ github.event.inputs.version }}\" else . end" > $pkgJson
+                        cat $pkgJson | jq "if .dependencies[\"$pkgName\"] then .dependencies[\"$pkgName\"] = \"${{ github.event.inputs.version }}\" else . end" > tmp
+                        mv tmp $pkgJson
+                        cat $pkgJson | jq "if .devDependencies[\"$pkgName\"] then .devDependencies[\"$pkgName\"] = \"${{ github.event.inputs.version }}\" else . end" > tmp
+                        mv tmp $pkgJson 
                     done
                 done
 
-                # update pkg lock
+                # the json may be poorly formatted now, so we need to fix it
                 npm i
+                npm run -w @prosopo/scripts build
+                npm run lint-fix:js
 
                 # commit the version changes
                 git add .
