adjust src branch check

diff --git a/.github/workflows/bump_version.yml b/.github/workflows/bump_version.yml
--- a/.github/workflows/bump_version.yml
+++ b/.github/workflows/bump_version.yml
@@ -111,20 +111,22 @@ jobs:
 
             - name: Bump version
               run: |
-                set -euox pipefail # stop on errors, print commands, fail on pipe fails
+                set -euo pipefail # stop on errors, print commands, fail on pipe fails
 
                 # set the author in git
                 git config user.name "prosoponator[bot]"
                 git config user.email "dev@prosopo.io"
 
-                # checkout the src branch
-                git checkout ${{ github.event.inputs.src }}
-                
                 # check the source branch (e.g. staging) is up-to-date with the dest branch (e.g. main)
-                if [ "$(git rev-list --count origin/${{ github.event.inputs.src }}..origin/${{ github.event.inputs.dest }})" -ne "0" ]; then
+                if [ "$(git rev-list --count origin/${{ github.event.inputs.src }}..origin/${{ github.event.inputs.dest }})" -ne 0 ]; then
                     echo "Source branch ${{ github.event.inputs.src }} is not up-to-date with destination branch ${{ github.event.inputs.dest }}. PR destination branch into the source branch and try again."
                     exit 1
+                else
+                    echo "Source branch ${{ github.event.inputs.src }} is up-to-date with destination branch ${{ github.event.inputs.dest }}"
                 fi
+
+                # checkout the src branch
+                git checkout ${{ github.event.inputs.src }}
 
                 INTERIM="${{ github.event.inputs.interim}}"
                 # set the interim branch name to release/<version_number> if not provided
