New git branches setup (#1296)
* add dev branch to auto merge

* make clippy run on new branch setup

* remove version checker workflow

* add dev and release branch triggers to consistent workflow name checker

* Delete create_diagram.yml

* add dev and release branch triggers to lint workflow

* add release and dev branch triggers to provider_image workflow

* remove release drafter

* add dev and release branches to rustfmt workflow

* add dev and release branches to protocol test workflow

* add dev and release branches triggers to tests workflow

* add dev and release branch triggers to webpack bundling workflow

* switch cache creation to be post pr to dev

* rename post_pr workflow to cache

* Update cache.yml

* publish workflow

* Update cache.yml

* fix contract js/rust version check workflow

* install concurrently and cypress as workspace deps

* fix cypress workflow trigger

* fix cypress workflow branch triggers

* fix rust file triggers

* move webpack bundling check to tests workflow

* remove typechain version check

* rename workflows

* make the github actions cache include the branch name

* publish on push to main

* add js bundle test step

* workflow for ensuring all versions move in lockstep

* blurb for each workflow

* dockerhub login check for before a release

* rename publish to release

* remove typedoc step

* standardise step ids in release workflow

* dummy version bump

* Delete dockerhub_login.yml

* release version check

* workflow to check for valid version bumps

* auto merge all prs

* check consistent workflow names on all prs

* branch system docs

* check contract version on prs to main,dev,release/*

* add workflow_dispatch to all relevant workflows

* make auto merge only run on non-draft prs

* check versions on all branches

* make release run on push to main

* tag pushes to main

* rename version check workflow

* remove fetch all history and branches from clone

* fix docker js server version issue

* fix bump workflow to bump all package.json files and Cargo.tomls

* fix package.json version writing in bump workflow

* rename step

* make auto merge cancellable

* make deploy ahve a single notification of pass/fail

* debug info

* fix cache workflow name

* don't use cache in bump version workflow, not needed

* move buildx to top of workflow

* move the cli building to before publishing images in deploy workflow

* tag warning

* remove filters for tests, test more often

* add workflow dispatch to deploy workflow

* add bash error catching

* Create consistent_engine_node.yml

* Create consistent_engine_npm.yml

* Create consistent_nvmrc.yml

* cache docs

* event workflows for main and dev

* change event setup

* don't run unless non-draft pr

* combine protocol clippy and rustfmt into single lint workflow

* missing engine

* missing version

* revert version debug

* fix version

* fix workflow name detection

* add missing engines

* fix nvmrc check

* fix path typo in contract version check

* allow auto merge to run always

* Update package-lock.json

* lint

* lint

diff --git a/.github/workflows/cache.yml b/.github/workflows/cache.yml
--- a/.github/workflows/cache.yml
+++ b/.github/workflows/cache.yml
@@ -1,11 +1,10 @@
-name: rustfmt
+# Build a cache of build artifacts after PRs to speed up subsequent builds
+
+name: cache
 
 on:
-    pull_request:
-        branches: [main]
-        paths:
-            - '**.rs'
-            - '.github/workflows/rustfmt.yml'
+    push:
+        branches: [main, dev]
     workflow_dispatch:
 
 concurrency:
@@ -14,11 +13,10 @@ concurrency:
 
 env:
     CARGO_TERM_COLOR: always
-    ENVIRONMENT: development
     GH_TOKEN: ${{ github.token }}
 
 jobs:
-    check:
+    build:
         runs-on: ubuntu-latest
         steps:
             - name: Print contexts
@@ -61,25 +59,13 @@ jobs:
 
             - uses: actions/checkout@v3
 
+            # make cache dirs
             - run: mkdir -p protocol/cargo-cache
             - run: mkdir -p protocol/target
             - run: mkdir -p node_modules
             - run: mkdir -p ~/.cache/Cypress
 
-            - name: Restore cache
-              uses: actions/cache/restore@v3
-              with:
-                  path: |
-                      protocol/cargo-cache
-                      protocol/target
-                      node_modules
-                      ~/.cache/Cypress
-                  # note that restoring a cache in github is a pain. The trailing '-' matches any string after the '-', therefore 'abc-' would match a cache named 'abc-1234' or 'abc-5678', etc.
-                  # the problem is 'abc-' will not match a cache named 'abc'! So if you're using wildcard cache name selectors like this, you need a field that changes as the suffix to become the wildcard
-                  # here we're setting the key to an unused cache key so it falls back to the wildcard selector in `restore-keys`
-                  key: some-unused-cache-key
-                  restore-keys: |
-                      project-cache-${{ runner.os }}-${{ runner.arch }}-
+            # don't restore the cache, otherwise we get artifacts left over from the previous run sit in the cache for eternity. Do a clean build every time.
 
             - uses: actions/setup-node@v3
               with:
@@ -89,3 +75,49 @@ jobs:
             - run: npm ci
 
             - run: npm -w @prosopo/protocol run rustfmt
+
+            - run: npm -w @prosopo/protocol run clippy
+
+            - run: npm -w @prosopo/protocol run build:all
+
+            - run: npm -w @prosopo/protocol run test:all
+
+            # install cypress so we don't have to do that every time
+            - name: Cypress install
+              run: |
+                  npm i --save-dev cypress
+                  npx cypress install
+
+            - run: ls -la ~/.cache/Cypress || true
+            - run: ls -la protocol/cargo-cache || true
+            - run: ls -la protocol/target/ink || true
+            - run: ls -la node_modules || true
+
+            # save cache to main branch. Any branch can use this cache afterwards to speed up their build
+            - name: Save cache
+              uses: actions/cache/save@v3
+              if: always()
+              with:
+                  path: |
+                      protocol/cargo-cache
+                      protocol/target
+                      node_modules
+                      ~/.cache/Cypress
+                  key: project-cache-${{ github.event.pull_request.head.ref || github.ref }}-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}-${{ github.run_attempt }}
+
+            # remove all but the latest cache, leaving only the cache we just saved
+            - name: Cleanup caches
+              if: always()
+              run: |
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+
+                    set +e; gh extension install actions/gh-actions-cache; set -e
+                    echo "Fetching list of cache key"
+                    cacheKeys=$(gh actions-cache list --sort created-at --order desc --limit 100 -R ${{ github.repository }} --key project-cache-${{ github.event.pull_request.head.ref || github.ref }}-${{ runner.os }}-${{ runner.arch }}- | cut -f 1 | tail -n +3)
+                    echo caches to be removed:
+                    echo ${cacheKeys}
+                    set +e
+                    for cacheKey in $cacheKeys
+                    do
+                        gh actions-cache delete $cacheKey -R ${{ github.repository }} --confirm
+                    done
diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,8 +1,10 @@
+# Lint the codebase
+
 name: lint
 
 on:
     pull_request:
-        branches: [main]
+        branches: [main, dev, release/*]
     workflow_dispatch:
 
 concurrency:
@@ -18,6 +20,7 @@ jobs:
     check:
         name: check
         runs-on: ubuntu-latest
+        if: github.event.pull_request.draft == false
         steps:
             - name: Print contexts
               env:
@@ -67,6 +70,7 @@ jobs:
             - name: Restore cache
               uses: actions/cache/restore@v3
               with:
+                  # must restore all cache dirs, and they must exist ahead of this!
                   path: |
                       protocol/cargo-cache
                       protocol/target
@@ -77,7 +81,7 @@ jobs:
                   # here we're setting the key to an unused cache key so it falls back to the wildcard selector in `restore-keys`
                   key: some-unused-cache-key
                   restore-keys: |
-                      project-cache-${{ runner.os }}-${{ runner.arch }}-
+                      project-cache-${{ github.event.pull_request.head.ref || github.ref }}-${{ runner.os }}-${{ runner.arch }}-
 
             - uses: actions/setup-node@v3
               with:
@@ -90,9 +94,11 @@ jobs:
 
             - name: lint
               run: |
-                  # get the files which have changed in the PR
-                  files=$(curl -L -s -H "Authorization: Bearer ${{ github.token }}" -H "Accept: application/vnd.github.v3+json" "${{ github.event.pull_request.url }}/files" | jq -r '.[] | .filename')
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                  echo "files: $files"
+                    # get the files which have changed in the PR
+                    files=$(curl -L -s -H "Authorization: Bearer ${{ github.token }}" -H "Accept: application/vnd.github.v3+json" "${{ github.event.pull_request.url }}/files" | jq -r '.[] | .filename')
 
-                  npm run lint:cmd -- $files
+                    echo "files: $files"
+
+                    npm run lint:cmd -- $files
