add bash error catching

diff --git a/.github/workflows/cache.yml b/.github/workflows/cache.yml
--- a/.github/workflows/cache.yml
+++ b/.github/workflows/cache.yml
@@ -109,6 +109,8 @@ jobs:
             - name: Cleanup caches
               if: always()
               run: |
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                   set +e; gh extension install actions/gh-actions-cache; set -e
                   echo "Fetching list of cache key"
                   cacheKeys=$(gh actions-cache list --sort created-at --order desc --limit 100 -R ${{ github.repository }} --key project-cache-${{ github.event.pull_request.head.ref || github.ref }}-${{ runner.os }}-${{ runner.arch }}- | cut -f 1 | tail -n +3)
diff --git a/.github/workflows/contract_version.yml b/.github/workflows/contract_version.yml
--- a/.github/workflows/contract_version.yml
+++ b/.github/workflows/contract_version.yml
@@ -66,7 +66,8 @@ jobs:
 
             - name: Check contract version matches provider version
               run: |
-                  set -eu
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                   # get the version of the contract in js pkg
                   for contract in contracts/*; do
                     echo "checking version in $contract"
diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -68,6 +68,8 @@ jobs:
               id: next_version
               run: |
 
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                   VERSION=$(cat package.json | jq -r '.version')
 
                   # if version not detected, error
@@ -116,6 +118,8 @@ jobs:
 
             - name: Build JS bundle
               run: |
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                   # Copy the rococo env file to production env file
                   echo "Copying the rococo env to production env file in procaptcha-bundle"
                   cp ./dev/scripts/env.production ./packages/procaptcha-bundle/.env.production
@@ -128,6 +132,8 @@ jobs:
 
             - name: Build docker js_server
               run: |
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                 # technically, if the release is for a version which is less than a published version, the following code will have bundles from versions ahead of this one. However, this isn't really a problem, as we just want the latest bundle to be available alongside old ones, not so bothered about newer ones.
 
                   # Set the JS location in the container
@@ -178,6 +184,8 @@ jobs:
 
             - name: Build the production CLI package
               run: |
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                   echo "Building the production CLI package..."
                   # Copy the rococo env file to production env file
                   echo "Copying the rococo env to production env file in cli package"
diff --git a/.github/workflows/provider_image.yml b/.github/workflows/provider_image.yml
--- a/.github/workflows/provider_image.yml
+++ b/.github/workflows/provider_image.yml
@@ -95,6 +95,8 @@ jobs:
             # build the cli production bundle
             - name: Build cli production bundle
               run: |
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                   cp ./dev/scripts/env.production ./packages/cli/.env.production
                   cp ./dev/scripts/env.production ./.env.production
                   NODE_ENV=production npm run -w @prosopo/cli bundle:prod
@@ -148,6 +150,8 @@ jobs:
             # Check that the version command works when running the bundle in the provider image
             - name: Check provider bundle runs
               run: |
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                   CONTAINER=$(docker run -d -v "./.env.production:/usr/src/app/.env.production" prosopo/provider:dev /bin/sh -c 'NODE_ENV=production npx provider version')
                   sleep 20s
                   docker logs $CONTAINER >& provider.log
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -98,6 +98,8 @@ jobs:
 
             - name: Build JS bundle
               run: |
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                   # Copy the rococo env file to production env file
                   echo "Copying the rococo env to production env file in procaptcha-bundle"
                   cp ./dev/scripts/env.production ./packages/procaptcha-bundle/.env.production
@@ -110,6 +112,8 @@ jobs:
 
             - name: Setup env
               run: |
+                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+                
                   cp demos/client-example-server/env.development demos/client-example-server/.env.test
                   cp demos/client-example/env.development demos/client-example/.env.test
                   cp dev/scripts/env.test .env.test
