Update check_version_bump.yml

diff --git a/.github/workflows/check_version_bump.yml b/.github/workflows/check_version_bump.yml
--- a/.github/workflows/check_version_bump.yml
+++ b/.github/workflows/check_version_bump.yml
@@ -63,8 +63,8 @@ jobs:
             # when running manually, there won't be a version line change, so we need to skip this step in that case
             - name: Detect version bump
               run: |
-                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
                   # get the next version as the version currently set in the root package.json
                   NEXT=$(jq -r '.version' package.json)
@@ -78,7 +78,7 @@ jobs:
                   echo "Previous version: $PREV"
 
                   # switch back to the current state
-                  git checkout ${{ github.sha }}
+                  git checkout ${{ github.event.after }}
 
                   # break next and previous versions into major, minor, patch
                   NEXT_MAJOR=$(echo $NEXT | cut -d. -f1)
