lint

diff --git a/.github/workflows/check_version_bump.yml b/.github/workflows/check_version_bump.yml
--- a/.github/workflows/check_version_bump.yml
+++ b/.github/workflows/check_version_bump.yml
@@ -60,40 +60,40 @@ jobs:
             # when running manually, there won't be a version line change, so we need to skip this step in that case
             - name: Detect version bump
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                # get the next version as the version currently set in the root package.json
-                NEXT=$(jq -r '.version' package.json)
-                echo "Next version: $NEXT"
 
-                # checkout the repo back to before this pr
-                git checkout ${{ github.event.before }}
+                  # get the next version as the version currently set in the root package.json
+                  NEXT=$(jq -r '.version' package.json)
+                  echo "Next version: $NEXT"
 
-                # get the previous version as the version currently set in the root package.json in the before state
-                PREV=$(jq -r '.version' package.json)
-                echo "Previous version: $PREV"
+                  # checkout the repo back to before this pr
+                  git checkout ${{ github.event.before }}
 
-                # switch back to the current state
-                git switch -
+                  # get the previous version as the version currently set in the root package.json in the before state
+                  PREV=$(jq -r '.version' package.json)
+                  echo "Previous version: $PREV"
 
-                # break next and previous versions into major, minor, patch
-                NEXT_MAJOR=$(echo $NEXT | cut -d. -f1)
-                NEXT_MINOR=$(echo $NEXT | cut -d. -f2)
-                NEXT_PATCH=$(echo $NEXT | cut -d. -f3)
-                PREV_MAJOR=$(echo $PREV | cut -d. -f1)
-                PREV_MINOR=$(echo $PREV | cut -d. -f2)
-                PREV_PATCH=$(echo $PREV | cut -d. -f3)
+                  # switch back to the current state
+                  git switch -
 
-                # compare the versions, checking for an *increasing* version
-                
-                if [[ $NEXT_MAJOR -gt $PREV_MAJOR ]]; then
-                    echo "Major version bump"
-                elif [[ $NEXT_MAJOR -eq $PREV_MAJOR && $NEXT_MINOR -gt $PREV_MINOR ]]; then
-                    echo "Minor version bump"
-                elif [[ $NEXT_MAJOR -eq $PREV_MAJOR && $NEXT_MINOR -eq $PREV_MINOR && $NEXT_PATCH -gt $PREV_PATCH ]]; then
-                    echo "Patch version bump"
-                else
-                    echo "Version not bumped / not an increasing version"
-                    exit 1
-                fi
+                  # break next and previous versions into major, minor, patch
+                  NEXT_MAJOR=$(echo $NEXT | cut -d. -f1)
+                  NEXT_MINOR=$(echo $NEXT | cut -d. -f2)
+                  NEXT_PATCH=$(echo $NEXT | cut -d. -f3)
+                  PREV_MAJOR=$(echo $PREV | cut -d. -f1)
+                  PREV_MINOR=$(echo $PREV | cut -d. -f2)
+                  PREV_PATCH=$(echo $PREV | cut -d. -f3)
+
+                  # compare the versions, checking for an *increasing* version
+
+                  if [[ $NEXT_MAJOR -gt $PREV_MAJOR ]]; then
+                      echo "Major version bump"
+                  elif [[ $NEXT_MAJOR -eq $PREV_MAJOR && $NEXT_MINOR -gt $PREV_MINOR ]]; then
+                      echo "Minor version bump"
+                  elif [[ $NEXT_MAJOR -eq $PREV_MAJOR && $NEXT_MINOR -eq $PREV_MINOR && $NEXT_PATCH -gt $PREV_PATCH ]]; then
+                      echo "Patch version bump"
+                  else
+                      echo "Version not bumped / not an increasing version"
+                      exit 1
+                  fi
diff --git a/.github/workflows/consistent_engine_npm.yml b/.github/workflows/consistent_engine_npm.yml
--- a/.github/workflows/consistent_engine_npm.yml
+++ b/.github/workflows/consistent_engine_npm.yml
@@ -66,17 +66,17 @@ jobs:
 
             - name: Check contract version matches provider version
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  # find all package.json files, recursively
-                  pkgJsons=$(find . -name package.json -prune -not -path '*/node_modules/*' -not -path '*/.next/*')
-                  
-                  # extract the npm version from the package.json files
-                    versions=$(jq -r '.engines.npm' $pkgJsons)
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                    # ensure all npm versions are the same
-                    if [ $(echo "$versions" | uniq | wc -l) -ne 1 ]; then
-                      echo "Npm versions are not consistent across packages"
-                      echo "$versions"
-                      exit 1
-                    fi
+                    # find all package.json files, recursively
+                    pkgJsons=$(find . -name package.json -prune -not -path '*/node_modules/*' -not -path '*/.next/*')
+                    
+                    # extract the npm version from the package.json files
+                      versions=$(jq -r '.engines.npm' $pkgJsons)
+
+                      # ensure all npm versions are the same
+                      if [ $(echo "$versions" | uniq | wc -l) -ne 1 ]; then
+                        echo "Npm versions are not consistent across packages"
+                        echo "$versions"
+                        exit 1
+                      fi
diff --git a/.github/workflows/consistent_workflow_names.yml b/.github/workflows/consistent_workflow_names.yml
--- a/.github/workflows/consistent_workflow_names.yml
+++ b/.github/workflows/consistent_workflow_names.yml
@@ -59,25 +59,25 @@ jobs:
 
             - name: Check workflow names
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  cd .github/workflows
-                  # Iterate through files in the current directory
-                  for file in *.yml *.yaml; do
-                      # Check if the item is a file (not a directory)
-                      if [[ -f "$file" ]]; then
-                        # find the first line beginning with "name:"
-                            first_line=$(grep -m 1 "^name:" "$file")
-                          
-                          # Extract name from the first line
-                          name=$(echo "$first_line" | awk -F ': ' '{print $2}')
-                          
-                          # Check if the extracted value matches the filename
-                          if [[ "$name" == "${file%.*}" ]]; then
-                              echo "File: $file - Name: $name (Match)"
-                          else
-                              echo "File: $file - Name: $name (No Match)"
-                              exit 1
-                          fi
-                      fi
-                  done
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+
+                    cd .github/workflows
+                    # Iterate through files in the current directory
+                    for file in *.yml *.yaml; do
+                        # Check if the item is a file (not a directory)
+                        if [[ -f "$file" ]]; then
+                          # find the first line beginning with "name:"
+                              first_line=$(grep -m 1 "^name:" "$file")
+                            
+                            # Extract name from the first line
+                            name=$(echo "$first_line" | awk -F ': ' '{print $2}')
+                            
+                            # Check if the extracted value matches the filename
+                            if [[ "$name" == "${file%.*}" ]]; then
+                                echo "File: $file - Name: $name (Match)"
+                            else
+                                echo "File: $file - Name: $name (No Match)"
+                                exit 1
+                            fi
+                        fi
+                    done
diff --git a/.github/workflows/contract_version.yml b/.github/workflows/contract_version.yml
--- a/.github/workflows/contract_version.yml
+++ b/.github/workflows/contract_version.yml
@@ -67,18 +67,18 @@ jobs:
 
             - name: Check contract version matches provider version
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  # get the version of the contract in js pkg
-                  for contract in contracts/*; do
-                    echo "checking version in $contract"
-                    jsVer=$(cat $contract/package.json | jq -r .version)
-                    echo "js version: $jsVer"
-                    # get the version of the contract in rust pkg
-                    # assuming the contract version is the first version line in Cargo.toml
-                    rustVer=$(cat protocol/$contract/Cargo.toml | grep -m 1 "version = " | cut -d '"' -f 2)
-                    if [[ "$jsVer" != "$rustVer" ]]; then
-                        echo "version mismatch: $jsVer != $rustVer"
-                        exit 1
-                    fi
-                  done
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+
+                    # get the version of the contract in js pkg
+                    for contract in contracts/*; do
+                      echo "checking version in $contract"
+                      jsVer=$(cat $contract/package.json | jq -r .version)
+                      echo "js version: $jsVer"
+                      # get the version of the contract in rust pkg
+                      # assuming the contract version is the first version line in Cargo.toml
+                      rustVer=$(cat protocol/$contract/Cargo.toml | grep -m 1 "version = " | cut -d '"' -f 2)
+                      if [[ "$jsVer" != "$rustVer" ]]; then
+                          echo "version mismatch: $jsVer != $rustVer"
+                          exit 1
+                      fi
+                    done
diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,7 +4,7 @@ name: deploy
 
 on:
     push:
-        branches: [ main ]
+        branches: [main]
     workflow_dispatch:
 
 jobs:
@@ -68,35 +68,35 @@ jobs:
               id: next_version
               run: |
 
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  VERSION=$(cat package.json | jq -r '.version')
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                  # if version not detected, error
-                    if [[ -z "$VERSION" ]]; then
-                        echo "Failed to get version"
-                        exit 1
-                    fi
-                    # or if version null
-                    if [[ "$VERSION" == "null" ]]; then
-                        echo "Failed to get version"
-                        exit 1
-                    fi
+                    VERSION=$(cat package.json | jq -r '.version')
 
-                  # split into major, minor, patch
-                  MAJOR=$(echo $VERSION | cut -d. -f1)
-                  MINOR=$(echo $VERSION | cut -d. -f2)
-                  PATCH=$(echo $VERSION | cut -d. -f3)
-                  echo "version=$VERSION"
-                  echo "major=$MAJOR"
-                  echo "minor=$MINOR"
-                  echo "patch=$PATCH"
+                    # if version not detected, error
+                      if [[ -z "$VERSION" ]]; then
+                          echo "Failed to get version"
+                          exit 1
+                      fi
+                      # or if version null
+                      if [[ "$VERSION" == "null" ]]; then
+                          echo "Failed to get version"
+                          exit 1
+                      fi
 
-                  # export the next version numbers
-                  echo "version=$VERSION" >> $GITHUB_OUTPUT
-                  echo "major=$MAJOR" >> $GITHUB_OUTPUT
-                  echo "minor=$MINOR" >> $GITHUB_OUTPUT
-                  echo "patch=$PATCH" >> $GITHUB_OUTPUT
+                    # split into major, minor, patch
+                    MAJOR=$(echo $VERSION | cut -d. -f1)
+                    MINOR=$(echo $VERSION | cut -d. -f2)
+                    PATCH=$(echo $VERSION | cut -d. -f3)
+                    echo "version=$VERSION"
+                    echo "major=$MAJOR"
+                    echo "minor=$MINOR"
+                    echo "patch=$PATCH"
+
+                    # export the next version numbers
+                    echo "version=$VERSION" >> $GITHUB_OUTPUT
+                    echo "major=$MAJOR" >> $GITHUB_OUTPUT
+                    echo "minor=$MINOR" >> $GITHUB_OUTPUT
+                    echo "patch=$PATCH" >> $GITHUB_OUTPUT
 
             - uses: actions/setup-node@v3
               with:
@@ -118,89 +118,89 @@ jobs:
 
             - name: Build JS bundle
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  # Copy the rococo env file to production env file
-                  echo "Copying the rococo env to production env file in procaptcha-bundle"
-                  cp ./dev/scripts/env.production ./packages/procaptcha-bundle/.env.production
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                  # Navigate to the JS bundle directory and build
-                  echo "Navigating to 'packages/procaptcha-bundle' and building JS bundle..."
-                  cd packages/procaptcha-bundle
+                    # Copy the rococo env file to production env file
+                    echo "Copying the rococo env to production env file in procaptcha-bundle"
+                    cp ./dev/scripts/env.production ./packages/procaptcha-bundle/.env.production
 
-                  NODE_ENV=production npm run bundle:prod
+                    # Navigate to the JS bundle directory and build
+                    echo "Navigating to 'packages/procaptcha-bundle' and building JS bundle..."
+                    cd packages/procaptcha-bundle
+
+                    NODE_ENV=production npm run bundle:prod
 
             - name: Build docker js_server
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                # technically, if the release is for a version which is less than a published version, the following code will have bundles from versions ahead of this one. However, this isn't really a problem, as we just want the latest bundle to be available alongside old ones, not so bothered about newer ones.
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                  # Set the JS location in the container
-                  JS_FOLDER="/usr/share/nginx/html/js"
+                  # technically, if the release is for a version which is less than a published version, the following code will have bundles from versions ahead of this one. However, this isn't really a problem, as we just want the latest bundle to be available alongside old ones, not so bothered about newer ones.
 
-                  # Get the most recent version of the js_server image
-                  docker pull prosopo/js_server:latest
+                    # Set the JS location in the container
+                    JS_FOLDER="/usr/share/nginx/html/js"
 
-                  # Create a temporary container from the latest image
-                  echo "Building Docker image..."
-                  OLD_CONTAINER_ID=$(docker create prosopo/js_server:$VERSION)
+                    # Get the most recent version of the js_server image
+                    docker pull prosopo/js_server:latest
 
-                  # Remove the old js temp folder
-                  rm -rf ./js_bundles_host_temp
+                    # Create a temporary container from the latest image
+                    echo "Building Docker image..."
+                    OLD_CONTAINER_ID=$(docker create prosopo/js_server:$VERSION)
 
-                  # Copy out the old files
-                  docker cp $OLD_CONTAINER_ID:$JS_FOLDER ./js_bundles_host_temp
+                    # Remove the old js temp folder
+                    rm -rf ./js_bundles_host_temp
 
-                  # Build the new image
-                  docker build --file ./docker/images/js.server.dockerfile . -t prosopo/js_server:${{ steps.next_version.outputs.version }} --no-cache
+                    # Copy out the old files
+                    docker cp $OLD_CONTAINER_ID:$JS_FOLDER ./js_bundles_host_temp
 
-                  # Run the new image
-                  NEW_CONTAINER_ID=$(docker create prosopo/js_server:${{ steps.next_version.outputs.version }})
+                    # Build the new image
+                    docker build --file ./docker/images/js.server.dockerfile . -t prosopo/js_server:${{ steps.next_version.outputs.version }} --no-cache
 
-                  # Copy the legacy files across
-                  docker cp ./js_bundles_host_temp/ $NEW_CONTAINER_ID:$JS_FOLDER/
+                    # Run the new image
+                    NEW_CONTAINER_ID=$(docker create prosopo/js_server:${{ steps.next_version.outputs.version }})
 
-                  # Copy the new bundle files to the container into a folder with the version name
-                  docker cp packages/procaptcha-bundle/dist/bundle/. $NEW_CONTAINER_ID:$JS_FOLDER
+                    # Copy the legacy files across
+                    docker cp ./js_bundles_host_temp/ $NEW_CONTAINER_ID:$JS_FOLDER/
 
-                  # Start the new container
-                  docker start $NEW_CONTAINER_ID
+                    # Copy the new bundle files to the container into a folder with the version name
+                    docker cp packages/procaptcha-bundle/dist/bundle/. $NEW_CONTAINER_ID:$JS_FOLDER
 
-                  # Move procaptcha.bundle.js
-                  docker exec $NEW_CONTAINER_ID mv $JS_FOLDER/procaptcha.bundle.js $JS_FOLDER/procaptcha.bundle.${{ steps.next_version.outputs.version }}.js
+                    # Start the new container
+                    docker start $NEW_CONTAINER_ID
 
-                  # Symlink JS_FOLDER/procaptcha.bundle.js to JS_FOLDER/procaptcha.bundle.VERSION.js
-                  docker exec $NEW_CONTAINER_ID ln -sf $JS_FOLDER/procaptcha.bundle.${{ steps.next_version.outputs.version }}.js $JS_FOLDER/procaptcha.bundle.js
+                    # Move procaptcha.bundle.js
+                    docker exec $NEW_CONTAINER_ID mv $JS_FOLDER/procaptcha.bundle.js $JS_FOLDER/procaptcha.bundle.${{ steps.next_version.outputs.version }}.js
 
-                  # Commit the changes to the container
-                  docker commit $NEW_CONTAINER_ID prosopo/js_server:${{ steps.next_version.outputs.version }}
+                    # Symlink JS_FOLDER/procaptcha.bundle.js to JS_FOLDER/procaptcha.bundle.VERSION.js
+                    docker exec $NEW_CONTAINER_ID ln -sf $JS_FOLDER/procaptcha.bundle.${{ steps.next_version.outputs.version }}.js $JS_FOLDER/procaptcha.bundle.js
 
-                  # Check this new docker image works locally
-                  docker run -d -p 3080:80 prosopo/js_server:${{ steps.next_version.outputs.version }}
+                    # Commit the changes to the container
+                    docker commit $NEW_CONTAINER_ID prosopo/js_server:${{ steps.next_version.outputs.version }}
 
-                  # Start the bundle demo & run the cypress tests against the new bundle
-                  # npx concurrently "npm run start:bundle" "npm run -w @prosopo/cypress-shared cypress:run:client-bundle-example:js_server" --success "first" --kill-others
+                    # Check this new docker image works locally
+                    docker run -d -p 3080:80 prosopo/js_server:${{ steps.next_version.outputs.version }}
+
+                    # Start the bundle demo & run the cypress tests against the new bundle
+                    # npx concurrently "npm run start:bundle" "npm run -w @prosopo/cypress-shared cypress:run:client-bundle-example:js_server" --success "first" --kill-others
 
             - name: Build the production CLI package
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  echo "Building the production CLI package..."
-                  # Copy the rococo env file to production env file
-                  echo "Copying the rococo env to production env file in cli package"
-                  cp ./dev/scripts/env.production ./packages/cli/.env.production
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                  # Navigate to the provider CLI directory and build
-                  echo "Navigating to 'packages/cli' and bundling..."
-                  cd packages/cli
-                  NODE_ENV=production npm run build
-                  NODE_ENV=production npm run bundle:prod
+                    echo "Building the production CLI package..."
+                    # Copy the rococo env file to production env file
+                    echo "Copying the rococo env to production env file in cli package"
+                    cp ./dev/scripts/env.production ./packages/cli/.env.production
 
-                  # Navigate back to the project root
-                  echo "Navigating back to project root..."
-                  cd ../..
-            
+                    # Navigate to the provider CLI directory and build
+                    echo "Navigating to 'packages/cli' and bundling..."
+                    cd packages/cli
+                    NODE_ENV=production npm run build
+                    NODE_ENV=production npm run bundle:prod
+
+                    # Navigate back to the project root
+                    echo "Navigating back to project root..."
+                    cd ../..
+
             # this will error if there's already a release for this version. This is by design, if you need to fix a release (e.g. because a deploy failed) then bump the version and try again
             - name: Github release
               id: github_release
@@ -261,11 +261,11 @@ jobs:
             - name: Deploy fail notification
               if: failure()
               run: |
-                echo "Deploy failed"
-                curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":check-failed: Deploy <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|v${{ steps.next_version.outputs.version }}> failed.\"}"  ${{ secrets.SLACKBOT_DEVOPS }}
+                  echo "Deploy failed"
+                  curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":check-failed: Deploy <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|v${{ steps.next_version.outputs.version }}> failed.\"}"  ${{ secrets.SLACKBOT_DEVOPS }}
 
             - name: Deploy success notification
               if: success()
               run: |
-                echo "Deploy succeeded"
-                curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":check-passed: Deploy <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|v${{ steps.next_version.outputs.version }}> succeeded.\"}"  ${{ secrets.SLACKBOT_DEVOPS }}
+                  echo "Deploy succeeded"
+                  curl -X POST -H 'Content-type: application/json' --data "{\"text\":\":check-passed: Deploy <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|v${{ steps.next_version.outputs.version }}> succeeded.\"}"  ${{ secrets.SLACKBOT_DEVOPS }}
diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -94,11 +94,11 @@ jobs:
 
             - name: lint
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  # get the files which have changed in the PR
-                  files=$(curl -L -s -H "Authorization: Bearer ${{ github.token }}" -H "Accept: application/vnd.github.v3+json" "${{ github.event.pull_request.url }}/files" | jq -r '.[] | .filename')
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                  echo "files: $files"
+                    # get the files which have changed in the PR
+                    files=$(curl -L -s -H "Authorization: Bearer ${{ github.token }}" -H "Accept: application/vnd.github.v3+json" "${{ github.event.pull_request.url }}/files" | jq -r '.[] | .filename')
 
-                  npm run lint:cmd -- $files
+                    echo "files: $files"
+
+                    npm run lint:cmd -- $files
diff --git a/.github/workflows/lockstep_version.yml b/.github/workflows/lockstep_version.yml
--- a/.github/workflows/lockstep_version.yml
+++ b/.github/workflows/lockstep_version.yml
@@ -69,21 +69,21 @@ jobs:
 
             - name: Check package versions are all moving in lockstep
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  # find all package.json files, recursively
-                  pkgJsons=$(find . -name package.json -prune -not -path '*/node_modules/*' -not -path '*/.next/*')
-                  # extract version from package.json files
-                  jsVers=$(xargs -I % sh -c "jq -r '.version' %" <<< "$pkgJsons")
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                  # find all Cargo.toml files
-                    cargoTomls=$(find . -name Cargo.toml -prune -not -path '*/protocol/cargo-cache/*')
-                  # extract the version out of all Cargo.toml files (we're assuming the version is the first version line encountered)
-                    rustVers=$(xargs -I % sh -c "grep -m 1 'version' % | awk -F'\"' '{print \$2}'" <<< "$cargoTomls")
-                    
-                  # compare all versions detected, if they are not all the same, fail the workflow
-                  vers=$(echo "$jsVers $rustVers" | tr ' ' '\n')
-                    if [[ $(echo "$vers" | uniq | wc -l) -ne 1 ]]; then
-                        echo "versions are not all the same: $vers"
-                        exit 1
-                    fi
+                    # find all package.json files, recursively
+                    pkgJsons=$(find . -name package.json -prune -not -path '*/node_modules/*' -not -path '*/.next/*')
+                    # extract version from package.json files
+                    jsVers=$(xargs -I % sh -c "jq -r '.version' %" <<< "$pkgJsons")
+
+                    # find all Cargo.toml files
+                      cargoTomls=$(find . -name Cargo.toml -prune -not -path '*/protocol/cargo-cache/*')
+                    # extract the version out of all Cargo.toml files (we're assuming the version is the first version line encountered)
+                      rustVers=$(xargs -I % sh -c "grep -m 1 'version' % | awk -F'\"' '{print \$2}'" <<< "$cargoTomls")
+                      
+                    # compare all versions detected, if they are not all the same, fail the workflow
+                    vers=$(echo "$jsVers $rustVers" | tr ' ' '\n')
+                      if [[ $(echo "$vers" | uniq | wc -l) -ne 1 ]]; then
+                          echo "versions are not all the same: $vers"
+                          exit 1
+                      fi
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -100,29 +100,29 @@ jobs:
 
             - name: Build JS bundle
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  # Copy the rococo env file to production env file
-                  echo "Copying the rococo env to production env file in procaptcha-bundle"
-                  cp ./dev/scripts/env.production ./packages/procaptcha-bundle/.env.production
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                  # Navigate to the JS bundle directory and build
-                  echo "Navigating to 'packages/procaptcha-bundle' and building JS bundle..."
-                  cd packages/procaptcha-bundle
+                    # Copy the rococo env file to production env file
+                    echo "Copying the rococo env to production env file in procaptcha-bundle"
+                    cp ./dev/scripts/env.production ./packages/procaptcha-bundle/.env.production
 
-                  NODE_ENV=production npm run bundle:prod
+                    # Navigate to the JS bundle directory and build
+                    echo "Navigating to 'packages/procaptcha-bundle' and building JS bundle..."
+                    cd packages/procaptcha-bundle
+
+                    NODE_ENV=production npm run bundle:prod
 
             - name: Setup env
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  cp demos/client-example-server/env.development demos/client-example-server/.env.test
-                  cp demos/client-example/env.development demos/client-example/.env.test
-                  cp dev/scripts/env.test .env.test
-                  cp dev/scripts/env.test dev/scripts/.env.test
-                  cp dev/scripts/env.test packages/cli/.env.test
-                  cp dev/scripts/env.test packages/procaptcha-bundle/.env.test
-                  echo NODE_ENV: $NODE_ENV
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+
+                    cp demos/client-example-server/env.development demos/client-example-server/.env.test
+                    cp demos/client-example/env.development demos/client-example/.env.test
+                    cp dev/scripts/env.test .env.test
+                    cp dev/scripts/env.test dev/scripts/.env.test
+                    cp dev/scripts/env.test packages/cli/.env.test
+                    cp dev/scripts/env.test packages/procaptcha-bundle/.env.test
+                    echo NODE_ENV: $NODE_ENV
 
             - name: Start the docker images
               run: |
