lint

diff --git a/.github/workflows/consistent_engine_node.yml b/.github/workflows/consistent_engine_node.yml
--- a/.github/workflows/consistent_engine_node.yml
+++ b/.github/workflows/consistent_engine_node.yml
@@ -66,17 +66,17 @@ jobs:
 
             - name: Check contract version matches provider version
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                  # find all package.json files, recursively
-                  pkgJsons=$(find . -name package.json -prune -not -path '*/node_modules/*' -not -path '*/.next/*')
-                  
-                  # extract the node version from the package.json files
-                    versions=$(jq -r '.engines.node' $pkgJsons)
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                    # ensure all node versions are the same
-                    if [ $(echo "$versions" | uniq | wc -l) -ne 1 ]; then
-                      echo "Node versions are not consistent across packages"
-                      echo "$versions"
-                      exit 1
-                    fi
+                    # find all package.json files, recursively
+                    pkgJsons=$(find . -name package.json -prune -not -path '*/node_modules/*' -not -path '*/.next/*')
+                    
+                    # extract the node version from the package.json files
+                      versions=$(jq -r '.engines.node' $pkgJsons)
+
+                      # ensure all node versions are the same
+                      if [ $(echo "$versions" | uniq | wc -l) -ne 1 ]; then
+                        echo "Node versions are not consistent across packages"
+                        echo "$versions"
+                        exit 1
+                      fi
diff --git a/.github/workflows/consistent_nvmrc.yml b/.github/workflows/consistent_nvmrc.yml
--- a/.github/workflows/consistent_nvmrc.yml
+++ b/.github/workflows/consistent_nvmrc.yml
@@ -67,25 +67,24 @@ jobs:
 
             - name: Check contract version matches provider version
               run: |
-                set -euxo pipefail # stop on errors, print commands, fail on pipe fails
-                
-                # find all .nvmrc files except in node_modules and get the content
-                nvmrcs=$(find . -name '.nvmrc' -not -path '*/node_modules/*' -exec cat {} +)
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                # check all .nvmrc files are the same content
-                if [ $(echo "$nvmrcs" | uniq | wc -l) -gt 1 ]; then
-                  echo "ERROR: .nvmrc files are not consistent"
-                  echo "$nvmrcs"
-                  exit 1
-                fi
+                  # find all .nvmrc files except in node_modules and get the content
+                  nvmrcs=$(find . -name '.nvmrc' -not -path '*/node_modules/*' -exec cat {} +)
 
-                # check nvmrc version matches engine, replacing <=> in the engine string with blank
-                engine=$(jq -r '.engines.node' package.json | tr -d '<>=')
+                  # check all .nvmrc files are the same content
+                  if [ $(echo "$nvmrcs" | uniq | wc -l) -gt 1 ]; then
+                    echo "ERROR: .nvmrc files are not consistent"
+                    echo "$nvmrcs"
+                    exit 1
+                  fi
 
-                if [ "$engine" != "$(cat .nvmrc)" ]; then
-                  echo "ERROR: .nvmrc version does not match engine"
-                  echo "engine: $engine"
-                  echo ".nvmrc: $(cat .nvmrc)"
-                  exit 1
-                fi
-                
+                  # check nvmrc version matches engine, replacing <=> in the engine string with blank
+                  engine=$(jq -r '.engines.node' package.json | tr -d '<>=')
+
+                  if [ "$engine" != "$(cat .nvmrc)" ]; then
+                    echo "ERROR: .nvmrc version does not match engine"
+                    echo "engine: $engine"
+                    echo ".nvmrc: $(cat .nvmrc)"
+                    exit 1
+                  fi
