New git branches setup (#1296)
* add dev branch to auto merge

* make clippy run on new branch setup

* remove version checker workflow

* add dev and release branch triggers to consistent workflow name checker

* Delete create_diagram.yml

* add dev and release branch triggers to lint workflow

* add release and dev branch triggers to provider_image workflow

* remove release drafter

* add dev and release branches to rustfmt workflow

* add dev and release branches to protocol test workflow

* add dev and release branches triggers to tests workflow

* add dev and release branch triggers to webpack bundling workflow

* switch cache creation to be post pr to dev

* rename post_pr workflow to cache

* Update cache.yml

* publish workflow

* Update cache.yml

* fix contract js/rust version check workflow

* install concurrently and cypress as workspace deps

* fix cypress workflow trigger

* fix cypress workflow branch triggers

* fix rust file triggers

* move webpack bundling check to tests workflow

* remove typechain version check

* rename workflows

* make the github actions cache include the branch name

* publish on push to main

* add js bundle test step

* workflow for ensuring all versions move in lockstep

* blurb for each workflow

* dockerhub login check for before a release

* rename publish to release

* remove typedoc step

* standardise step ids in release workflow

* dummy version bump

* Delete dockerhub_login.yml

* release version check

* workflow to check for valid version bumps

* auto merge all prs

* check consistent workflow names on all prs

* branch system docs

* check contract version on prs to main,dev,release/*

* add workflow_dispatch to all relevant workflows

* make auto merge only run on non-draft prs

* check versions on all branches

* make release run on push to main

* tag pushes to main

* rename version check workflow

* remove fetch all history and branches from clone

* fix docker js server version issue

* fix bump workflow to bump all package.json files and Cargo.tomls

* fix package.json version writing in bump workflow

* rename step

* make auto merge cancellable

* make deploy ahve a single notification of pass/fail

* debug info

* fix cache workflow name

* don't use cache in bump version workflow, not needed

* move buildx to top of workflow

* move the cli building to before publishing images in deploy workflow

* tag warning

* remove filters for tests, test more often

* add workflow dispatch to deploy workflow

* add bash error catching

* Create consistent_engine_node.yml

* Create consistent_engine_npm.yml

* Create consistent_nvmrc.yml

* cache docs

* event workflows for main and dev

* change event setup

* don't run unless non-draft pr

* combine protocol clippy and rustfmt into single lint workflow

* missing engine

* missing version

* revert version debug

* fix version

* fix workflow name detection

* add missing engines

* fix nvmrc check

* fix path typo in contract version check

* allow auto merge to run always

* Update package-lock.json

* lint

* lint

diff --git a/.github/workflows/consistent_nvmrc.yml b/.github/workflows/consistent_nvmrc.yml
--- a/.github/workflows/consistent_nvmrc.yml
+++ b/.github/workflows/consistent_nvmrc.yml
@@ -1,16 +1,24 @@
-# Check workflow names are consistent with their filenames for easier debugging
+# Check the npm versions are consistent across packages
 
-name: consistent_workflow_names
+name: consistent_nvmrc
 
 on:
     pull_request:
-        # only when workflow file is changed
-        paths: ['.github/workflows/**']
+        branches: [main, dev, release/*]
+        paths:
+            - '**/package.json'
+            - '**/.nvmrc'
+            - '.github/workflows/consistent_engine_node_and_nvmrc.yml'
     workflow_dispatch:
 
 concurrency:
     group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
     cancel-in-progress: true
+
+env:
+    CARGO_TERM_COLOR: always
+    ENVIRONMENT: development
+    GH_TOKEN: ${{ github.token }}
 
 jobs:
     check:
@@ -57,27 +65,26 @@ jobs:
 
             - uses: actions/checkout@v3
 
-            - name: Check workflow names
+            - name: Check contract version matches provider version
               run: |
                   set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-                    cd .github/workflows
-                    # Iterate through files in the current directory
-                    for file in *.yml *.yaml; do
-                        # Check if the item is a file (not a directory)
-                        if [[ -f "$file" ]]; then
-                          # find the first line beginning with "name:"
-                              first_line=$(grep -m 1 "^name:" "$file")
-                            
-                            # Extract name from the first line
-                            name=$(echo "$first_line" | awk -F ': ' '{print $2}')
-                            
-                            # Check if the extracted value matches the filename
-                            if [[ "$name" == "${file%.*}" ]]; then
-                                echo "File: $file - Name: $name (Match)"
-                            else
-                                echo "File: $file - Name: $name (No Match)"
-                                exit 1
-                            fi
-                        fi
-                    done
+                  # find all .nvmrc files except in node_modules and get the content
+                  nvmrcs=$(find . -name '.nvmrc' -not -path '*/node_modules/*' -exec cat {} +)
+
+                  # check all .nvmrc files are the same content
+                  if [ $(echo "$nvmrcs" | uniq | wc -l) -gt 1 ]; then
+                    echo "ERROR: .nvmrc files are not consistent"
+                    echo "$nvmrcs"
+                    exit 1
+                  fi
+
+                  # check nvmrc version matches engine, replacing <=> in the engine string with blank
+                  engine=$(jq -r '.engines.node' package.json | tr -d '<>=')
+
+                  if [ "$engine" != "$(cat .nvmrc)" ]; then
+                    echo "ERROR: .nvmrc version does not match engine"
+                    echo "engine: $engine"
+                    echo ".nvmrc: $(cat .nvmrc)"
+                    exit 1
+                  fi
diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -1,15 +1,10 @@
+# Run cypress tests
+
 name: cypress
 
 on:
     pull_request:
-        branches: [main]
-        paths:
-            - 'docker/**'
-            - 'packages/**'
-            - 'demos/**'
-            - 'dev/**'
-            - 'contracts/**'
-            - '.github/workflows/tests.yml'
+        branches: [main, dev, release/*]
     workflow_dispatch:
 
 concurrency:
@@ -24,6 +19,7 @@ env:
 jobs:
     check:
         runs-on: ubuntu-latest
+        if: github.event.pull_request.draft == false
         steps:
             - name: Print contexts
               env:
@@ -73,6 +69,7 @@ jobs:
             - name: Restore cache
               uses: actions/cache/restore@v3
               with:
+                  # must restore all cache dirs, and they must exist ahead of this!
                   path: |
                       protocol/cargo-cache
                       protocol/target
@@ -83,7 +80,7 @@ jobs:
                   # here we're setting the key to an unused cache key so it falls back to the wildcard selector in `restore-keys`
                   key: some-unused-cache-key
                   restore-keys: |
-                      project-cache-${{ runner.os }}-${{ runner.arch }}-
+                      project-cache-${{ github.event.pull_request.head.ref || github.ref }}-${{ runner.os }}-${{ runner.arch }}-
 
             - uses: actions/setup-node@v3
               with:
@@ -97,13 +94,15 @@ jobs:
 
             - name: Setup env
               run: |
-                  cp demos/client-example-server/env.development demos/client-example-server/.env.test
-                  cp demos/client-example/env.development demos/client-example/.env.test
-                  cp dev/scripts/env.test .env.test
-                  cp dev/scripts/env.test dev/scripts/.env.test
-                  cp dev/scripts/env.test packages/cli/.env.test
-                  cp dev/scripts/env.test packages/procaptcha-bundle/.env.test
-                  echo NODE_ENV: $NODE_ENV
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+
+                    cp demos/client-example-server/env.development demos/client-example-server/.env.test
+                    cp demos/client-example/env.development demos/client-example/.env.test
+                    cp dev/scripts/env.test .env.test
+                    cp dev/scripts/env.test dev/scripts/.env.test
+                    cp dev/scripts/env.test packages/cli/.env.test
+                    cp dev/scripts/env.test packages/procaptcha-bundle/.env.test
+                    echo NODE_ENV: $NODE_ENV
 
             - name: Start the docker images
               run: |
@@ -119,10 +118,6 @@ jobs:
             # Running bundle:dev instead of bundle:prod means the bundle will be built with selectors that can be used
             # by the cypress tests to find the elements they need to interact with
             - run: NODE_ENV=test npm -w @prosopo/procaptcha-bundle run bundle:dev
-
-            # Needs concurrently to avoid vite hanging forever https://github.com/vitejs/vite/discussions/8745
-            - name: Install concurrently and cypress
-              run: npm i concurrently cypress
 
             - name: Run the cypress tests on client-example
               run: |
