lint

diff --git a/.github/workflows/consistent_versions.yml b/.github/workflows/consistent_versions.yml
--- a/.github/workflows/consistent_versions.yml
+++ b/.github/workflows/consistent_versions.yml
@@ -29,21 +29,20 @@ jobs:
 
             - name: Check versions are consistent amongst packages
               run: |
-                # for each package, get the version then filter to unique versions
-                versions=$(npx --workspaces npm pkg get version | grep "@" | awk '{print $2}' | uniq)
-                # if more than one version is detected, fail
-                if [ $(echo "$versions" | wc -l) -gt 1 ]; then
-                    echo "Versions are not consistent amongst packages:"
-                    echo "$versions"
-                    exit 1
-                fi
-                # if version doesn't match the root workspace version, fail
-                root_version=$(npm pkg get version)
-                if [ "$versions" != "$root_version" ]; then
-                    echo "Version is not consistent with root workspace version:"
-                    echo "$versions"
-                    echo "$root_version"
-                    exit 1
-                fi
-                # else versions are consistent, pass
-
+                  # for each package, get the version then filter to unique versions
+                  versions=$(npx --workspaces npm pkg get version | grep "@" | awk '{print $2}' | uniq)
+                  # if more than one version is detected, fail
+                  if [ $(echo "$versions" | wc -l) -gt 1 ]; then
+                      echo "Versions are not consistent amongst packages:"
+                      echo "$versions"
+                      exit 1
+                  fi
+                  # if version doesn't match the root workspace version, fail
+                  root_version=$(npm pkg get version)
+                  if [ "$versions" != "$root_version" ]; then
+                      echo "Version is not consistent with root workspace version:"
+                      echo "$versions"
+                      echo "$root_version"
+                      exit 1
+                  fi
+                  # else versions are consistent, pass
