New git branches setup (#1296)
* add dev branch to auto merge

* make clippy run on new branch setup

* remove version checker workflow

* add dev and release branch triggers to consistent workflow name checker

* Delete create_diagram.yml

* add dev and release branch triggers to lint workflow

* add release and dev branch triggers to provider_image workflow

* remove release drafter

* add dev and release branches to rustfmt workflow

* add dev and release branches to protocol test workflow

* add dev and release branches triggers to tests workflow

* add dev and release branch triggers to webpack bundling workflow

* switch cache creation to be post pr to dev

* rename post_pr workflow to cache

* Update cache.yml

* publish workflow

* Update cache.yml

* fix contract js/rust version check workflow

* install concurrently and cypress as workspace deps

* fix cypress workflow trigger

* fix cypress workflow branch triggers

* fix rust file triggers

* move webpack bundling check to tests workflow

* remove typechain version check

* rename workflows

* make the github actions cache include the branch name

* publish on push to main

* add js bundle test step

* workflow for ensuring all versions move in lockstep

* blurb for each workflow

* dockerhub login check for before a release

* rename publish to release

* remove typedoc step

* standardise step ids in release workflow

* dummy version bump

* Delete dockerhub_login.yml

* release version check

* workflow to check for valid version bumps

* auto merge all prs

* check consistent workflow names on all prs

* branch system docs

* check contract version on prs to main,dev,release/*

* add workflow_dispatch to all relevant workflows

* make auto merge only run on non-draft prs

* check versions on all branches

* make release run on push to main

* tag pushes to main

* rename version check workflow

* remove fetch all history and branches from clone

* fix docker js server version issue

* fix bump workflow to bump all package.json files and Cargo.tomls

* fix package.json version writing in bump workflow

* rename step

* make auto merge cancellable

* make deploy ahve a single notification of pass/fail

* debug info

* fix cache workflow name

* don't use cache in bump version workflow, not needed

* move buildx to top of workflow

* move the cli building to before publishing images in deploy workflow

* tag warning

* remove filters for tests, test more often

* add workflow dispatch to deploy workflow

* add bash error catching

* Create consistent_engine_node.yml

* Create consistent_engine_npm.yml

* Create consistent_nvmrc.yml

* cache docs

* event workflows for main and dev

* change event setup

* don't run unless non-draft pr

* combine protocol clippy and rustfmt into single lint workflow

* missing engine

* missing version

* revert version debug

* fix version

* fix workflow name detection

* add missing engines

* fix nvmrc check

* fix path typo in contract version check

* allow auto merge to run always

* Update package-lock.json

* lint

* lint

diff --git a/.github/workflows/contract_version.yml b/.github/workflows/contract_version.yml
--- a/.github/workflows/contract_version.yml
+++ b/.github/workflows/contract_version.yml
@@ -1,8 +1,10 @@
+# Check the contract JS is in sync with the Rust version
+
 name: contract_version
 
 on:
     pull_request:
-        branches: [main]
+        branches: [main, dev, release/*]
         paths:
             - '**/package.json'
             - '**/Cargo.toml'
@@ -21,6 +23,7 @@ env:
 jobs:
     check:
         runs-on: ubuntu-latest
+        if: github.event.pull_request.draft == false
         steps:
             - name: Print contexts
               env:
@@ -64,13 +67,18 @@ jobs:
 
             - name: Check contract version matches provider version
               run: |
-                  set -eu
-                    provider=$(cat packages/provider/package.json | jq -r '.version')
-                    find protocol/target/ink/*/ -name "Cargo.toml" | while read line; do
-                        contract=$(cat $line | grep -m 1 "version = " | cut -d '"' -f 2)
-                        echo "checking version in $line"
-                        if [[ "$contract" != "$provider" ]]; then
-                            echo "version mismatch: $contract != $provider"
-                            exit 1
-                        fi
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+
+                    # get the version of the contract in js pkg
+                    for contract in contracts/*; do
+                      echo "checking version in $contract"
+                      jsVer=$(cat $contract/package.json | jq -r .version)
+                      echo "js version: $jsVer"
+                      # get the version of the contract in rust pkg
+                      # assuming the contract version is the first version line in Cargo.toml
+                      rustVer=$(cat protocol/$contract/Cargo.toml | grep -m 1 "version = " | cut -d '"' -f 2)
+                      if [[ "$jsVer" != "$rustVer" ]]; then
+                          echo "version mismatch: $jsVer != $rustVer"
+                          exit 1
+                      fi
                     done
diff --git a/.github/workflows/lockstep_version.yml b/.github/workflows/lockstep_version.yml
--- a/.github/workflows/lockstep_version.yml
+++ b/.github/workflows/lockstep_version.yml
@@ -1,11 +1,16 @@
-name: webpack_bundling
+# Workflow to check all versions of packages are the same, ensuring we move in lockstep.
+# We made the decision to move in lockstep for greater dev speed at the detriment of more frequent version bumps than necessary to some packages.
+# Lockstep versioning is simpler and doesn't require backwards compatibility headaches.
+
+name: lockstep_version
 
 on:
     pull_request:
-        branches: [main]
+        branches: [main, dev, release/*]
         paths:
-            - 'src/**'
-            - 'package.json'
+            - '**/package.json'
+            - '**/Cargo.toml'
+            - '.github/workflows/lockstep_version.yml'
     workflow_dispatch:
 
 concurrency:
@@ -14,12 +19,13 @@ concurrency:
 
 env:
     CARGO_TERM_COLOR: always
+    ENVIRONMENT: development
     GH_TOKEN: ${{ github.token }}
-    NODE_ENV: test
 
 jobs:
     check:
         runs-on: ubuntu-latest
+        if: github.event.pull_request.draft == false
         steps:
             - name: Print contexts
               env:
@@ -58,42 +64,26 @@ jobs:
                   echo "******************************"
                   echo "inputs:" "$INPUTS_CONTEXT"
                   echo "******************************"
-            # Checkout the repo
+
             - uses: actions/checkout@v3
 
-            - run: mkdir -p protocol/cargo-cache
-            - run: mkdir -p protocol/target
-            - run: mkdir -p node_modules
-            - run: mkdir -p ~/.cache/Cypress
-
-            - name: Restore cache
-              uses: actions/cache/restore@v3
-              with:
-                  path: |
-                      protocol/cargo-cache
-                      protocol/target
-                      node_modules
-                      ~/.cache/Cypress
-                  # note that restoring a cache in github is a pain. The trailing '-' matches any string after the '-', therefore 'abc-' would match a cache named 'abc-1234' or 'abc-5678', etc.
-                  # the problem is 'abc-' will not match a cache named 'abc'! So if you're using wildcard cache name selectors like this, you need a field that changes as the suffix to become the wildcard
-                  # here we're setting the key to an unused cache key so it falls back to the wildcard selector in `restore-keys`
-                  key: some-unused-cache-key
-                  restore-keys: |
-                      project-cache-${{ runner.os }}-${{ runner.arch }}-
-
-            - uses: actions/setup-node@v3
-              with:
-                  node-version-file: '.nvmrc'
-            - name: Install npm
-              run: npm i -g npm@$(cat package.json | jq -r .engines.npm)
-
-            - run: npm install
-
-            # build all packages in workspace
-            - run: npm run build scripts
-            - run: npm run build:all:cjs
-
-            # bundle procaptcha-bundle using webpack
-            - name: Webpack Bundle procaptcha-bundle
+            - name: Check package versions are all moving in lockstep
               run: |
-                  npm run -w @prosopo/procaptcha-bundle bundle:dev:webpack
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+
+                    # find all package.json files, recursively
+                    pkgJsons=$(find . -name package.json -prune -not -path '*/node_modules/*' -not -path '*/.next/*')
+                    # extract version from package.json files
+                    jsVers=$(xargs -I % sh -c "jq -r '.version' %" <<< "$pkgJsons")
+
+                    # find all Cargo.toml files
+                      cargoTomls=$(find . -name Cargo.toml -prune -not -path '*/protocol/cargo-cache/*')
+                    # extract the version out of all Cargo.toml files (we're assuming the version is the first version line encountered)
+                      rustVers=$(xargs -I % sh -c "grep -m 1 'version' % | awk -F'\"' '{print \$2}'" <<< "$cargoTomls")
+                      
+                    # compare all versions detected, if they are not all the same, fail the workflow
+                    vers=$(echo "$jsVers $rustVers" | tr ' ' '\n')
+                      if [[ $(echo "$vers" | uniq | wc -l) -ne 1 ]]; then
+                          echo "versions are not all the same: $vers"
+                          exit 1
+                      fi
