Revert "fix/npm scripts (#1956)"
This reverts commit c27bdee9dea608857bb51bcc1ff49b22f369fb4c.

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -3,115 +3,119 @@
 name: cypress
 
 on:
-  pull_request:
-    branches: [main, dev, staging, release/*]
-    types:
-      - opened # when a PR is opened
-      - synchronize # when a PR is pushed to
-      - reopened # when a PR is reopened
-      - ready_for_review # when a PR is marked as ready for review (e.g. taken off draft mode)
-  workflow_dispatch:
+    pull_request:
+        branches: [main, dev, staging, release/*]
+        types:
+            - opened # when a PR is opened
+            - synchronize # when a PR is pushed to
+            - reopened # when a PR is reopened
+            - ready_for_review # when a PR is marked as ready for review (e.g. taken off draft mode)
+    workflow_dispatch:
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
-  cancel-in-progress: true
+    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+    cancel-in-progress: true
 
 env:
-  GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
-  GH_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
-  CARGO_TERM_COLOR: always
-  NODE_OPTIONS: "--max-old-space-size=4096"
-  NODE_ENV: "test"
+    GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
+    GH_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
+    CARGO_TERM_COLOR: always
+    NODE_OPTIONS: "--max-old-space-size=4096"
+    NODE_ENV: "test"
 
 defaults:
-  run:
-    shell: bash
+    run:
+        shell: bash
 
 jobs:
-  check:
-    runs-on: ubuntu-latest
-    if: github.event.pull_request.draft == false
-    steps:
-      - name: Print contexts
-        uses: prosopo/captcha/.github/actions/print_contexts@gha
-        with:
-          INPUTS_CONTEXT: ${{ toJson(inputs) }}
-          NEEDS_CONTEXT: ${{ toJson(needs) }}
-          VARS_CONTEXT: ${{ toJson(vars) }}
-          SECRETS_CONTEXT: ${{ toJson(secrets) }}
+    check:
+        runs-on: ubuntu-latest
+        if: github.event.pull_request.draft == false
+        steps:
+            - name: Print contexts
+              uses: prosopo/captcha/.github/actions/print_contexts@gha
+              with:
+                INPUTS_CONTEXT: ${{ toJson(inputs) }}
+                NEEDS_CONTEXT: ${{ toJson(needs) }}
+                VARS_CONTEXT: ${{ toJson(vars) }}
+                SECRETS_CONTEXT: ${{ toJson(secrets) }}
 
-      - name: Set NX_PARALLEL environment variable
-        run: echo "NX_PARALLEL=$(nproc)" >> $GITHUB_ENV
+            - name: Set NX_PARALLEL environment variable
+              run: echo "NX_PARALLEL=$(nproc)" >> $GITHUB_ENV
 
-      - uses: actions/checkout@v4
-        with:
-          submodules: "recursive"
+            - uses: actions/checkout@v4
+              with:
+                  submodules: "recursive"
 
-      - uses: prosopo/captcha/.github/actions/npm@gha
-        with:
-          npm_ci_args: '--include=dev'
+            - uses: prosopo/captcha/.github/actions/npm@gha
+              with:
+                npm_ci_args: '--include=dev'
 
-      - name: Setup env
-        run: |
-          set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+            # build the packages required by vite build commands first
+            - run: npm run -w @prosopo/config build
+            - run: npm run -w @prosopo/dotenv build
 
-          cp demos/client-example-server/env.development demos/client-example-server/.env.test
-          cp demos/client-bundle-example/env.development demos/client-bundle-example/.env.test
-          cp dev/scripts/env.test .env.test
-          cp dev/scripts/env.test dev/scripts/.env.test
-          cp dev/scripts/env.test packages/cli/.env.test
-          cp dev/scripts/env.test packages/procaptcha-bundle/.env.test
-          echo NODE_ENV: "$NODE_ENV"
+            # build all packages in workspace
+            - run: npm run build:all
 
-      # build all packages in workspace
-      - run: npm run build:all
+            - name: Setup env
+              run: |
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-      - name: Start the docker images
-        run: |
-          docker compose --file ./docker/docker-compose.test.yml up -d --remove-orphans --force-recreate --always-recreate-deps
-          docker container ls
-          sleep 10s
+                    cp demos/client-example-server/env.development demos/client-example-server/.env.test
+                    cp demos/client-bundle-example/env.development demos/client-bundle-example/.env.test
+                    cp dev/scripts/env.test .env.test
+                    cp dev/scripts/env.test dev/scripts/.env.test
+                    cp dev/scripts/env.test packages/cli/.env.test
+                    cp dev/scripts/env.test packages/procaptcha-bundle/.env.test
+                    echo NODE_ENV: "$NODE_ENV"
 
-      # deploy dapp + protocol and run setup to register, stake and load a dataset for a provider
-      - run: NODE_ENV="test" npm run setup
+            - name: Start the docker images
+              run: |
+                  docker compose --file ./docker/docker-compose.test.yml up -d --remove-orphans --force-recreate --always-recreate-deps
+                  docker container ls
+                  sleep 10s
 
-      # Build a test version of the procaptcha bundle and run the cypress tests on it and on the React client-example
-      # Running using NODE_ENV=development instead of NODE_ENV=production means the bundle will be built with selectors that can be used
-      # by the cypress tests to find the elements they need to interact with
-      - run: NODE_ENV="development" npm -w @prosopo/procaptcha-bundle run build:bundle
+            # deploy dapp + protocol and run setup to register, stake and load a dataset for a provider
+            - run: NODE_ENV="test" npm run setup
 
-      - name: Run the cypress tests on client-bundle-example
-        run: |
-          npx concurrently "npm run start:server" "npm run start:provider:admin" "npm run start:bundle" "npm run serve:bundle" "sleep 10s && npm -w @prosopo/cypress-shared run cypress:run:client-bundle-example:image" --success "first" --kill-others
+            # Build a test version of the procaptcha bundle and run the cypress tests on it and on the React client-example
+            # Running using NODE_ENV=development instead of NODE_ENV=production means the bundle will be built with selectors that can be used
+            # by the cypress tests to find the elements they need to interact with
+            - run: NODE_ENV="development" npm -w @prosopo/procaptcha-bundle run bundle
 
-      - name: Run the cypress tests on client-bundle-example explicit rendering with frictionless captcha
-        run: |
-          npx concurrently "npm run start:server" "npm run start:provider:admin" "npm run start:bundle" "npm run serve:bundle" "sleep 10s && npm -w @prosopo/cypress-shared run cypress:run:client-bundle-example:frictionless" --success "first" --kill-others
+            - name: Run the cypress tests on client-bundle-example
+              run: |
+                  npx concurrently "npm run start:server" "npm run start:provider:admin" "npm run start:bundle" "npm run serve:bundle" "sleep 10s && npm -w @prosopo/cypress-shared run cypress:run:client-bundle-example:image" --success "first" --kill-others
 
-      - name: Run the cypress tests on client-bundle-example explicit rendering with pow captcha
-        run: |
-          npx concurrently "npm run start:server" "npm run start:provider:admin" "npm run start:bundle" "npm run serve:bundle" "sleep 10s && npm -w @prosopo/cypress-shared run cypress:run:client-bundle-example:pow" --success "first" --kill-others
+            - name: Run the cypress tests on client-bundle-example explicit rendering with frictionless captcha
+              run: |
+                  npx concurrently "npm run start:server" "npm run start:provider:admin" "npm run start:bundle" "npm run serve:bundle" "sleep 10s && npm -w @prosopo/cypress-shared run cypress:run:client-bundle-example:frictionless" --success "first" --kill-others
 
-      - name: Run the cypress tests on client-bundle-example explicit rendering with invisible captcha
-        run: |
-          npx concurrently "npm run start:server" "npm run start:provider:admin" "npm run start:bundle" "npm run serve:bundle" "sleep 10s && npm -w @prosopo/cypress-shared run cypress:run:client-bundle-example:invisible" --success "first" --kill-others
+            - name: Run the cypress tests on client-bundle-example explicit rendering with pow captcha
+              run: |
+                  npx concurrently "npm run start:server" "npm run start:provider:admin" "npm run start:bundle" "npm run serve:bundle" "sleep 10s && npm -w @prosopo/cypress-shared run cypress:run:client-bundle-example:pow" --success "first" --kill-others
 
-      # after the test run completes store videos and any screenshots
-      - uses: actions/upload-artifact@v4
-        # store screenshots only on failures
-        if: failure()
-        with:
-          name: cypress-screenshots
-          path: ./demos/cypress-shared/cypress/screenshots
-          if-no-files-found: ignore  # 'warn' or 'error' are also available, defaults to `warn`
+            - name: Run the cypress tests on client-bundle-example explicit rendering with invisible captcha
+              run: |
+                  npx concurrently "npm run start:server" "npm run start:provider:admin" "npm run start:bundle" "npm run serve:bundle" "sleep 10s && npm -w @prosopo/cypress-shared run cypress:run:client-bundle-example:invisible" --success "first" --kill-others
 
-      # after the test run completes store videos and any screenshots
-      - uses: actions/upload-artifact@v4
-        # store videos only on failures
-        if: failure()
-        with:
-          name: cypress-videos
-          path: ./demos/cypress-shared/cypress/videos
-          if-no-files-found: ignore   # 'warn' or 'error' are also available, defaults to `warn`
+            # after the test run completes store videos and any screenshots
+            - uses: actions/upload-artifact@v4
+              # store screenshots only on failures
+              if: failure()
+              with:
+                  name: cypress-screenshots
+                  path: ./demos/cypress-shared/cypress/screenshots
+                  if-no-files-found: ignore  # 'warn' or 'error' are also available, defaults to `warn`
 
-      - run: docker compose --file ./docker/docker-compose.test.yml down
+            # after the test run completes store videos and any screenshots
+            - uses: actions/upload-artifact@v4
+              # store videos only on failures
+              if: failure()
+              with:
+                  name: cypress-videos
+                  path: ./demos/cypress-shared/cypress/videos
+                  if-no-files-found: ignore   # 'warn' or 'error' are also available, defaults to `warn`
+
+            - run: docker compose --file ./docker/docker-compose.test.yml down
diff --git a/.github/workflows/provider_image.yml b/.github/workflows/provider_image.yml
--- a/.github/workflows/provider_image.yml
+++ b/.github/workflows/provider_image.yml
@@ -3,99 +3,105 @@
 name: provider_image
 
 on:
-  pull_request:
-    branches: [main, dev, staging, release/*]
-    types:
-      - opened # when a PR is opened
-      - synchronize # when a PR is pushed to
-      - reopened # when a PR is reopened
-      - ready_for_review # when a PR is marked as ready for review (e.g. taken off draft mode)
-  workflow_dispatch:
+    pull_request:
+        branches: [main, dev, staging, release/*]
+        types:
+            - opened # when a PR is opened
+            - synchronize # when a PR is pushed to
+            - reopened # when a PR is reopened
+            - ready_for_review # when a PR is marked as ready for review (e.g. taken off draft mode)
+    workflow_dispatch:
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
-  cancel-in-progress: true
+    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+    cancel-in-progress: true
 
 env:
-  GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
-  GH_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
-  CARGO_TERM_COLOR: always
-  NODE_OPTIONS: "--max-old-space-size=4096"
+    GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
+    GH_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
+    CARGO_TERM_COLOR: always
+    NODE_OPTIONS: "--max-old-space-size=4096"
 
 defaults:
-  run:
-    shell: bash
+    run:
+        shell: bash
 
 jobs:
-  check:
-    runs-on: ubuntu-latest
-    if: github.event.pull_request.draft == false
-    steps:
-      - name: Print contexts
-        uses: prosopo/captcha/.github/actions/print_contexts@gha
-        with:
-          INPUTS_CONTEXT: ${{ toJson(inputs) }}
-          NEEDS_CONTEXT: ${{ toJson(needs) }}
-          VARS_CONTEXT: ${{ toJson(vars) }}
-          SECRETS_CONTEXT: ${{ toJson(secrets) }}
+    check:
+        runs-on: ubuntu-latest
+        if: github.event.pull_request.draft == false
+        steps:
+            - name: Print contexts
+              uses: prosopo/captcha/.github/actions/print_contexts@gha
+              with:
+                INPUTS_CONTEXT: ${{ toJson(inputs) }}
+                NEEDS_CONTEXT: ${{ toJson(needs) }}
+                VARS_CONTEXT: ${{ toJson(vars) }}
+                SECRETS_CONTEXT: ${{ toJson(secrets) }}
 
-      - name: Set NX_PARALLEL environment variable
-        run: echo "NX_PARALLEL=$(nproc)" >> $GITHUB_ENV
+            - name: Set NX_PARALLEL environment variable
+              run: echo "NX_PARALLEL=$(nproc)" >> $GITHUB_ENV
 
-      - uses: actions/checkout@v4
-        with:
-          submodules: "recursive"
+            - uses: actions/checkout@v4
+              with:
+                  submodules: "recursive"
 
-      - uses: prosopo/captcha/.github/actions/npm@gha
-        with:
-          npm_ci_args: '--include=dev'
+            - uses: prosopo/captcha/.github/actions/npm@gha
+              with:
+                npm_ci_args: '--include=dev'
 
-      - name: env
-        run: |
-          cp ./dev/scripts/env.production ./packages/cli/.env.production
-          cp ./dev/scripts/env.production ./.env.production
-          # copy the development PROVIDER_MNEMONIC from ./dev/scripts/env.development to .env.production
-          echo $(grep -PoIe "PROSOPO_PROVIDER_MNEMONIC.*" ./dev/scripts/env.development) > .env.production
+            # build all the packages in the workspace to prepare assets for the next cli bundle command
+            - name: Build packages
+              run: |
+                npm run build:all
 
-      # build all the packages in the workspace to prepare assets for the next cli bundle command
-      - name: Build packages
-        run: |
-          NODE_ENV="production" npm run build:all
+            # build the cli production bundle
+            - name: Build cli production bundle
+              run: |
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+                    cp ./dev/scripts/env.production ./packages/cli/.env.production
+                    cp ./dev/scripts/env.production ./.env.production
+                    # copy the development PROVIDER_MNEMONIC from ./dev/scripts/env.development to .env.production
+                    echo $(grep -PoIe "PROSOPO_PROVIDER_MNEMONIC.*" ./dev/scripts/env.development) > .env.production
+                    NODE_ENV="production" npm run -w @prosopo/cli bundle
 
-      # We cannot create the images in a single step because the output of buildx is not compatible with
-      # `docker load`. https://stackoverflow.com/a/72952846/1178971
+            - name: Set up Docker Buildx
+              uses: docker/setup-buildx-action@v3
 
-      # create the provider image for AMD64
-      - name: Build the Provider Container
-        uses: docker/build-push-action@v5
-        with:
-          context: ${{github.workspace}}
-          file: ${{github.workspace}}/docker/images/provider/src/Dockerfile
-          platforms: linux/amd64
-          push: false
-          tags: prosopo/provider:dev
-          outputs: type=docker,dest=provider-amd64.tar
+            # We cannot create the images in a single step because the output of buildx is not compatible with
+            # `docker load`. https://stackoverflow.com/a/72952846/1178971
 
-      # load the AMD64 image
-      - name: Load the Provider Container
-        run: docker load -i provider-amd64.tar
+            # create the provider image for AMD64
+            - name: Build the Provider Container
+              id: build_docker_provider_amd64
+              continue-on-error: false
+              uses: docker/build-push-action@v5
+              with:
+                  context: ${{github.workspace}}
+                  file: ${{github.workspace}}/docker/images/provider.dockerfile
+                  platforms: linux/amd64
+                  push: false
+                  tags: prosopo/provider:dev
+                  outputs: type=docker,dest=provider-amd64.tar
 
-      # Generate a mnemonic for the provider image
-      - name: Generate mnemonic and add to env file
-        run: |
-          PROSOPO_ROOT_DIR=$(pwd) NODE_ENV="production" node dev/scripts/dist/scripts/generateMnemonic.js --env
+            # load the AMD64 image
+            - name: Load the Provider Container
+              run: docker load -i provider-amd64.tar
 
-      # Check that the version command works when running the bundle in the provider image
-      - name: Check provider bundle runs
-        run: |
-          set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+            # Generate a mnemonic for the provider image
+            - name: Generate mnemonic and add to env file
+              run: |
+                  PROSOPO_ROOT_DIR=$(pwd) NODE_ENV="production" node dev/scripts/dist/scripts/generateMnemonic.js --env
 
-            CONTAINER="$(docker run -d -v "./.env.production:/usr/src/app/.env.production" prosopo/provider:dev /bin/sh -c 'NODE_ENV=production npx provider version')"
-            sleep 20s
-            docker logs "$CONTAINER" >& provider.log
-            cat provider.log
-            grep -oE "\"version\":\".*\"" provider.log || exit 1
+            # Check that the version command works when running the bundle in the provider image
+            - name: Check provider bundle runs
+              run: |
+                  set -euxo pipefail # stop on errors, print commands, fail on pipe fails
+
+                    CONTAINER="$(docker run -d -v "./.env.production:/usr/src/app/.env.production" prosopo/provider:dev /bin/sh -c 'NODE_ENV=production npx provider version')"
+                    sleep 20s
+                    docker logs "$CONTAINER" >& provider.log
+                    cat provider.log
+                    grep -oE "Version: \\\\\".*\\\\\"" provider.log || (cat provider.log && exit 1)
 
