less than logic instead of less than or equal

diff --git a/.github/workflows/npm_release_process.yml b/.github/workflows/npm_release_process.yml
--- a/.github/workflows/npm_release_process.yml
+++ b/.github/workflows/npm_release_process.yml
@@ -44,28 +44,23 @@ jobs:
                   restore-keys: |
                       project-cache-${{ runner.os }}-${{ runner.arch }}-
 
-            # Check if the provider image version is greater than the latest version on the npm package @prosopo/provider
-            # For example, if the provider image version is 0.1.7 and the latest npm version is 0.1.6, then the provider image
-            # version is greater. If the provider image version is 0.1.6 and the latest npm version is 0.1.6, then the provider
-            # image version is not greater, and the workflow will not continue unless the provider image version is updated in
-            # the root package.json. Technically, this check doesn't cover the case where the provider image version is lower
-            # than the latest npm version, but that should never happen.
             - name: Check provider image version
               id: check_provider_image_version
               run: |
                   echo "PROVIDER_IMAGE_VERSION=${{ env.PROVIDER_IMAGE_VERSION }}"
                   echo "LATEST_PROVIDER_VERSION=${{ env.LATEST_PROVIDER_VERSION }}"
 
-                  # Condition 1: If version is less than the npm version, exit with error
-                  if [[ $(echo -e "${{ env.VERSIONS_TO_COMPARE }}" | sort -V | head -n 1) == "${{ env.PROVIDER_IMAGE_VERSION }}" ]]; then
-                      echo "Version bump required, exiting with error"
-                      exit 1
-                  fi
-
-                  # Condition 2: If version is equal to the npm version, exit successfully
+                  # Condition 1: If version is equal to the npm version, exit successfully
                   if [[ "${{ env.PROVIDER_IMAGE_VERSION }}" == "${{ env.LATEST_PROVIDER_VERSION }}" ]]; then
                       echo "Current npm version detected, exiting successfully"
                       exit 0
+                  fi
+
+                  # Condition 2: If version is less than the npm version, exit with error
+                  # Technically this is less than or equal, but we have checked for equality above
+                  if [[ $(echo -e "${{ env.VERSIONS_TO_COMPARE }}" | sort -V | head -n 1) == "${{ env.PROVIDER_IMAGE_VERSION }}" ]]; then
+                      echo "Version bump required, exiting with error"
+                      exit 1
                   fi
 
                   # Condition 3: If greater than npm version, release to npm if running on GitHub Actions
