make docker pull latest version of js_server rather than current_version to handle failed deployments gracefully

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -165,12 +165,22 @@ jobs:
                   echo "Logging into Docker Hub."
                   echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 2> /dev/null
 
-                  # Pull the latest Docker image
-                  docker pull prosopo/js_server:${{steps.check_version.outputs.current_version}}
+                  # Pull the latest Docker image. Note that this may not be the same version as the current version of main if the docker image did not get deployed for that version, e.g. due to a failed build
+                  # therefore, we have to lookup the latest version manually rather than relying on the version in package.json on main
+                  # find the version which is the predecessor to the next version
+                  latest=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/prosopo/js_server/tags/' | jq ".results[].name" | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+" | sort | grep -B 1 ${{ steps.check_version.outputs.next_version }} | head -n 1)
+
+                  # check latest has been detected correctly (i.e. isn't empty)
+                  if [[ -z "$latest" ]]; then
+                    echo "Failed to find latest version"
+                    exit 1
+                  fi
+
+                  docker pull prosopo/js_server:$latest
 
                   # Create a temporary container from the latest image
                   echo "Building Docker image..."
-                  CONTAINER_ID=$(docker create prosopo/js_server:${{steps.check_version.outputs.current_version}})
+                  CONTAINER_ID=$(docker create prosopo/js_server:$latest)
 
                   # Copy the bundle to the container and rename it to include the version
                   docker cp packages/procaptcha-bundle/dist/bundle/procaptcha.bundle.js $CONTAINER_ID:/usr/share/nginx/html/js/procaptcha.bundle.${{ steps.check_version.outputs.next_version }}.js
