Fix deploy triggers (#913)
* add build typechain step

* lint

* add ignore_version_check input for workflow dispatch, adjust bump variable accordingly

* lint

* make every deploy step always run, even if the previous fails

* move docker login

* restructure publishing to always publish each channel

* make docker pull latest version of js_server rather than current_version to handle failed deployments gracefully

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -94,12 +94,6 @@ jobs:
             - run: ls -la protocol/target/ink || true
             - run: ls -la node_modules || true
 
-            - name: Log in to Docker Hub
-              if: steps.check_version.outputs.bump == 'true'
-              run: |
-                  echo "Logging into Docker Hub."
-                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 2> /dev/null
-
             - name: Install
               run: |
                   npm install
@@ -108,7 +102,6 @@ jobs:
             # at this point there should be a build in the cache, so we can begin building artifacts for the release
 
             - name: Install dependencies and build packages
-              if: steps.check_version.outputs.bump == 'true'
               run: |
                   echo "Installing dependencies..."
                   npm ci
@@ -117,7 +110,6 @@ jobs:
                   npm run build:all:cjs
 
             - name: Build the contract sources
-              if: steps.check_version.outputs.bump == 'true'
               run: |
                   cd protocol/dev
                   npm run build
@@ -125,7 +117,6 @@ jobs:
                   npm run cli -- build --docker --release
 
             - name: Build JS bundle
-              if: steps.check_version.outputs.bump == 'true'
               run: |
                   # Copy the rococo env file to production env file
                   echo "Copying the rococo env to production env file in procaptcha-bundle"
@@ -137,7 +128,16 @@ jobs:
 
                   NODE_ENV=production npm run bundle:prod
 
+            # by here we should have all the artifacts we need to publish. If any have experienced an error during build, we should skip publishing
+            # this step will be skipped if the build above has failed at any point
+            - name: Set publish var
+              id: publish
+              run: |
+                  echo "Setting publish var..."
+                  echo "publish=true" >> $GITHUB_OUTPUT
+
             - name: Publish to github
+              if: always() && steps.publish.outputs.publish == 'true'
               env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               run: |
@@ -145,7 +145,7 @@ jobs:
                   gh release create --generate-notes "v${{ steps.check_version.outputs.next_version }}" "./protocol/target/ink/captcha/captcha.contract" "./protocol/target/ink/proxy/proxy.contract" "./packages/procaptcha-bundle/dist/bundle/procaptcha.bundle.js"
 
             - name: Npm publish
-              if: steps.check_version.outputs.bump == 'true'
+              if: always() && steps.publish.outputs.publish == 'true'
               run: |
                   if [[ "${{ vars.HOST_GITHUB_ACTIONS }}" == true ]]; then
                     echo "Running on GitHub Actions"
@@ -160,14 +160,27 @@ jobs:
                   fi
 
             - name: Publish bundle in js_server to dockerhub
-              if: steps.check_version.outputs.bump == 'true'
+              if: always() && steps.publish.outputs.publish == 'true'
               run: |
-                  # Pull the latest Docker image
-                  docker pull prosopo/js_server:${{steps.check_version.outputs.current_version}}
+                  echo "Logging into Docker Hub."
+                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 2> /dev/null
+
+                  # Pull the latest Docker image. Note that this may not be the same version as the current version of main if the docker image did not get deployed for that version, e.g. due to a failed build
+                  # therefore, we have to lookup the latest version manually rather than relying on the version in package.json on main
+                  # find the version which is the predecessor to the next version
+                  latest=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/prosopo/js_server/tags/' | jq ".results[].name" | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+" | sort | grep -B 1 ${{ steps.check_version.outputs.next_version }} | head -n 1)
+
+                  # check latest has been detected correctly (i.e. isn't empty)
+                  if [[ -z "$latest" ]]; then
+                    echo "Failed to find latest version"
+                    exit 1
+                  fi
+
+                  docker pull prosopo/js_server:$latest
 
                   # Create a temporary container from the latest image
                   echo "Building Docker image..."
-                  CONTAINER_ID=$(docker create prosopo/js_server:${{steps.check_version.outputs.current_version}})
+                  CONTAINER_ID=$(docker create prosopo/js_server:$latest)
 
                   # Copy the bundle to the container and rename it to include the version
                   docker cp packages/procaptcha-bundle/dist/bundle/procaptcha.bundle.js $CONTAINER_ID:/usr/share/nginx/html/js/procaptcha.bundle.${{ steps.check_version.outputs.next_version }}.js
@@ -184,7 +197,7 @@ jobs:
 
             - name: Build and Push the Provider Bundle
               # Build and push the provider bundle to Docker Hub if bump is true
-              if: steps.check_version.outputs.bump == 'true'
+              if: always() && steps.publish.outputs.publish == 'true'
               run: |
                   # Copy the rococo env file to production env file
                   echo "Copying the rococo env to production env file in cli package"
