publish workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -8,8 +8,6 @@ on:
         paths:
             # only when the package.json file changes
             - 'package.json'
-    # or run manually
-    workflow_dispatch:
 
 jobs:
     publish:
@@ -53,51 +51,19 @@ jobs:
                   echo "inputs:" "$INPUTS_CONTEXT"
                   echo "******************************"
 
-            - uses: actions/checkout@v3
-              with:
-                  # fetch all history + branches
-                  fetch-depth: 0
-
             - name: Dockerhub login
               run: |
                   echo "Logging into Docker Hub."
                   echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 2> /dev/null
 
-            # fail-fast step to check if the version has been bumped
-            # when running manually, there won't be a version line change, so we need to skip this step in that case
-            - name: Detect version bump
+            - uses: actions/checkout@v3
+              with:
+                  # fetch all history + branches
+                  fetch-depth: 0
+
+            - name: Next version
               id: next_version
               run: |
-                  if [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
-                    echo "manual run, skipping version check"
-                    exit 0
-                  fi
-
-                  # use git to look for differences in package.json between the before and after state
-                  # before and after git sha's are passed in as env vars by github
-                  diff=$(git show --pretty=format: --no-notes ${{ github.event.before }}..${{ github.event.after }} -- package.json | cat)
-                  echo "diff:"
-                  echo "$diff"
-                  echo ""
-
-                  # grep for the version line
-                  version_changes=$(echo "$diff" | grep -e "[-\+]\s*\"version\"" || true)
-                  echo "version_changes:"
-                  echo "$version_changes"
-                  echo ""
-
-                  # if the version line has changed then we know there's been a version change. Not necessarily bumped up, though!
-                  # the next version will be whatever is currently in the package.json file
-                  # subsequent steps can choose whether the version has been bumped or not. All we know at this stage is the version has been changed, i.e. new_version != old_version, but we don't know whether new_version > old_version or new_version < old_version
-                  if [[ -n "$version_changes" ]]; then
-                    echo "version has changed"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  else
-                    echo "version has not changed"
-                    # skip remaining steps which bump the version
-                    echo "bump=false" >> $GITHUB_OUTPUT
-                    exit 0
-                  fi
 
                   VERSION=$(cat package.json | jq -r '.version' || echo "0.0.0")
                   # split into major, minor, patch
@@ -115,237 +81,22 @@ jobs:
                   echo "minor=$MINOR" >> $GITHUB_OUTPUT
                   echo "patch=$PATCH" >> $GITHUB_OUTPUT
 
-            # check for version bump against github release
-            - name: Check version github
-              id: check_version_github
-              if: steps.next_version.outputs.bump == 'true'
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-              run: |
-                  # get the current version number from latest release on gh
-                  VERSION=$(gh release list --limit 1 | awk '{print $1}' | tr -d v)
-
-                  if [[ -z "$VERSION" ]]; then
-                    echo "Failed to get current version"
-                    exit 1
-                  fi
-
-                  MAJOR=$(echo $VERSION | cut -d. -f1)
-                  MINOR=$(echo $VERSION | cut -d. -f2)
-                  PATCH=$(echo $VERSION | cut -d. -f3)
-                  echo "version=$VERSION" >> $GITHUB_OUTPUT
-                  echo "major=$MAJOR" >> $GITHUB_OUTPUT
-                  echo "minor=$MINOR" >> $GITHUB_OUTPUT
-                  echo "patch=$PATCH" >> $GITHUB_OUTPUT
-                  echo "version: $VERSION"
-
-                  if [[ "${{ steps.next_version.outputs.major }}" -gt "$MAJOR" ]]; then
-                    echo "major version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  elif [[ "${{ steps.next_version.outputs.minor }}" -gt "$MINOR" ]]; then
-                    echo "minor version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  elif [[ "${{ steps.next_version.outputs.patch }}" -gt "$PATCH" ]]; then
-                    echo "patch version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  else
-                    echo "no version bump detected"
-                    echo "bump=false" >> $GITHUB_OUTPUT
-                  fi
-
-            - name: Check version npm
-              id: check_version_npm
-              if: steps.next_version.outputs.bump == 'true'
-              run: |
-                  # get the current version number from latest release on npm (use procaptcha as the baseline, as workspace package is not published)
-                  VERSION=$(npm view @prosopo/procaptcha version)
-
-                  if [[ -z "$VERSION" ]]; then
-                    echo "Failed to get current version"
-                    exit 1
-                  fi
-
-                  MAJOR=$(echo $VERSION | cut -d. -f1)
-                  MINOR=$(echo $VERSION | cut -d. -f2)
-                  PATCH=$(echo $VERSION | cut -d. -f3)
-                  echo "version=$VERSION" >> $GITHUB_OUTPUT
-                  echo "major=$MAJOR" >> $GITHUB_OUTPUT
-                  echo "minor=$MINOR" >> $GITHUB_OUTPUT
-                  echo "patch=$PATCH" >> $GITHUB_OUTPUT
-                  echo "version: $VERSION"
-
-                  if [[ "${{ steps.next_version.outputs.major }}" -gt "$MAJOR" ]]; then
-                    echo "major version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  elif [[ "${{ steps.next_version.outputs.minor }}" -gt "$MINOR" ]]; then
-                    echo "minor version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  elif [[ "${{ steps.next_version.outputs.patch }}" -gt "$PATCH" ]]; then
-                    echo "patch version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  else
-                    echo "no version bump detected"
-                    echo "bump=false" >> $GITHUB_OUTPUT
-                  fi
-
-            - name: Check version docker js_server
-              id: check_version_docker_js_server
-              if: steps.next_version.outputs.bump == 'true'
-              run: |
-                  # get the current version number from latest release on docker
-                  VERSION=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/prosopo/js_server/tags/' | jq ".results[].name" | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+" | head -n 1)
-
-                  if [[ -z "$VERSION" ]]; then
-                    echo "Failed to get current version"
-                    exit 1
-                  fi
-
-                  MAJOR=$(echo $VERSION | cut -d. -f1)
-                  MINOR=$(echo $VERSION | cut -d. -f2)
-                  PATCH=$(echo $VERSION | cut -d. -f3)
-                  echo "version=$VERSION" >> $GITHUB_OUTPUT
-                  echo "major=$MAJOR" >> $GITHUB_OUTPUT
-                  echo "minor=$MINOR" >> $GITHUB_OUTPUT
-                  echo "patch=$PATCH" >> $GITHUB_OUTPUT
-                  echo "version: $VERSION"
-
-                  if [[ "${{ steps.next_version.outputs.major }}" -gt "$MAJOR" ]]; then
-                    echo "major version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  elif [[ "${{ steps.next_version.outputs.minor }}" -gt "$MINOR" ]]; then
-                    echo "minor version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  elif [[ "${{ steps.next_version.outputs.patch }}" -gt "$PATCH" ]]; then
-                    echo "patch version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  else
-                    echo "no version bump detected"
-                    echo "bump=false" >> $GITHUB_OUTPUT
-                  fi
-
-            - name: Check version docker provider
-              id: check_version_docker_provider
-              if: steps.next_version.outputs.bump == 'true'
-              run: |
-                  # get the current version number from latest release on docker
-                  VERSION=$(curl -L -s 'https://registry.hub.docker.com/v2/repositories/prosopo/provider/tags/' | jq ".results[].name" | grep -E -o "[0-9]+\.[0-9]+\.[0-9]+" | head -n 1)
-
-                  if [[ -z "$VERSION" ]]; then
-                    echo "Failed to get current version"
-                    exit 1
-                  fi
-
-                  MAJOR=$(echo $VERSION | cut -d. -f1)
-                  MINOR=$(echo $VERSION | cut -d. -f2)
-                  PATCH=$(echo $VERSION | cut -d. -f3)
-                  echo "version=$VERSION" >> $GITHUB_OUTPUT
-                  echo "major=$MAJOR" >> $GITHUB_OUTPUT
-                  echo "minor=$MINOR" >> $GITHUB_OUTPUT
-                  echo "patch=$PATCH" >> $GITHUB_OUTPUT
-                  echo "version: $VERSION"
-
-                  if [[ "${{ steps.next_version.outputs.major }}" -gt "$MAJOR" ]]; then
-                    echo "major version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  elif [[ "${{ steps.next_version.outputs.minor }}" -gt "$MINOR" ]]; then
-                    echo "minor version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  elif [[ "${{ steps.next_version.outputs.patch }}" -gt "$PATCH" ]]; then
-                    echo "patch version bump detected"
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                  else
-                    echo "no version bump detected"
-                    echo "bump=false" >> $GITHUB_OUTPUT
-                  fi
-
-            - name: Should bump?
-              id: check_version_any
-              run: |
-                  bump=false
-                  # only bump if any of the version checks have detected a bump
-                  if [[ "${{ steps.check_version_github.outputs.bump }}" == 'true' ]]; then
-                    bump=true
-                    echo "github bump required"
-                  fi
-                  if [[ "${{ steps.check_version_npm.outputs.bump }}" == 'true' ]]; then
-                    bump=true
-                    echo "npm bump required"
-                  fi
-                  if [[ "${{ steps.check_version_docker_js_server.outputs.bump }}" == 'true' ]]; then
-                    bump=true
-                    echo "docker js_server bump required"
-                  fi
-                  if [[ "${{ steps.check_version_docker_provider.outputs.bump }}" == 'true' ]]; then
-                    bump=true
-                    echo "docker provider bump required"
-                  fi
-                  if [[ "$bump" == 'true' ]]; then
-                    echo "bump=true" >> $GITHUB_OUTPUT
-                    echo "something needs bumping"
-                  else
-                    echo "bump=false" >> $GITHUB_OUTPUT
-                    echo "nothing needs bumping"
-                  fi
-
-            # get the latest build from the cache produced in the post_pr workflow
-
-            - run: mkdir -p protocol/cargo-cache
-              if: steps.check_version_any.outputs.bump == 'true'
-            - run: mkdir -p protocol/target
-              if: steps.check_version_any.outputs.bump == 'true'
-            - run: mkdir -p node_modules
-              if: steps.check_version_any.outputs.bump == 'true'
-            - run: mkdir -p ~/.cache/Cypress
-              if: steps.check_version_any.outputs.bump == 'true'
-
-            - name: Restore cache
-              if: steps.check_version_any.outputs.bump == 'true'
-              uses: actions/cache/restore@v3
-              with:
-                  path: |
-                      protocol/cargo-cache
-                      protocol/target
-                      node_modules
-                      ~/.cache/Cypress
-                  # note that restoring a cache in github is a pain. The trailing '-' matches any string after the '-', therefore 'abc-' would match a cache named 'abc-1234' or 'abc-5678', etc.
-                  # the problem is 'abc-' will not match a cache named 'abc'! So if you're using wildcard cache name selectors like this, you need a field that changes as the suffix to become the wildcard
-                  # here we're setting the key to an unused cache key so it falls back to the wildcard selector in `restore-keys`
-                  key: some-unused-cache-key
-                  restore-keys: |
-                      project-cache-${{ runner.os }}-${{ runner.arch }}-
-
-            - run: ls -la ~/.cache/Cypress || true
-              if: steps.check_version_any.outputs.bump == 'true'
-            - run: ls -la protocol/cargo-cache || true
-              if: steps.check_version_any.outputs.bump == 'true'
-            - run: ls -la protocol/target/ink || true
-              if: steps.check_version_any.outputs.bump == 'true'
-            - run: ls -la node_modules || true
-              if: steps.check_version_any.outputs.bump == 'true'
-
             - uses: actions/setup-node@v3
-              if: steps.check_version_any.outputs.bump == 'true'
               with:
                   node-version-file: '.nvmrc'
             - run: npm i -g npm@$(cat package.json | jq -r .engines.npm)
-              if: steps.check_version_any.outputs.bump == 'true'
 
-            - name: Install
-              if: steps.check_version_any.outputs.bump == 'true'
-              run: |
-                  npm ci
+            - run: npm ci
 
-            # at this point there should be a build in the cache, so we can begin building artifacts for the release
+            # build from scratch to ensure nothing bought over from cache
 
             - name: Build packages
-              if: steps.check_version_any.outputs.bump == 'true'
               run: |
                   echo "Building packages..."
                   npm run build:all
                   npm run build:all:cjs
 
             - name: Build the contract sources
-              if: steps.check_version_any.outputs.bump == 'true'
               run: |
                   cd protocol/dev
                   npm run build
@@ -357,7 +108,6 @@ jobs:
                   npm run docs
 
             - name: Build JS bundle
-              if: steps.check_version_any.outputs.bump == 'true'
               run: |
                   # Copy the rococo env file to production env file
                   echo "Copying the rococo env to production env file in procaptcha-bundle"
@@ -370,17 +120,28 @@ jobs:
                   NODE_ENV=production npm run bundle:prod
 
             - name: Build docker js_server
-              if: steps.check_version_any.outputs.bump == 'true'
               run: |
                   # Set the JS location in the container
                   JS_FOLDER="/usr/share/nginx/html/js"
 
                   # Get the most recent version of the js_server image
-                  docker pull prosopo/js_server:${{ steps.check_version_docker_js_server.outputs.version }}
+                  docker pull prosopo/js_server:${{ steps.next_version.outputs.version }}
+
+                  # get the previous version number from latest release on docker
+                  VERSION=$(cd dev/gh-actions && npx tsx src/previousDockerTag.ts prosopo js_server ${{ steps.next_version.outputs.version }})
+
+                  if [[ -z "$VERSION" ]]; then
+                    echo "Failed to get previous version"
+                    exit 1
+                  fi
+
+                  MAJOR=$(echo $VERSION | cut -d. -f1)
+                  MINOR=$(echo $VERSION | cut -d. -f2)
+                  PATCH=$(echo $VERSION | cut -d. -f3)
 
                   # Create a temporary container from the latest image
                   echo "Building Docker image..."
-                  OLD_CONTAINER_ID=$(docker create prosopo/js_server:${{ steps.check_version_docker_js_server.outputs.version }})
+                  OLD_CONTAINER_ID=$(docker create prosopo/js_server:$VERSION)
 
                   # Remove the old js temp folder
                   rm -rf ./js_bundles_host_temp
@@ -421,7 +182,6 @@ jobs:
             - name: Github release
               continue-on-error: true
               id: publish_github
-              if: steps.check_version_github.outputs.bump == 'true'
               env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               run: |
@@ -444,7 +204,6 @@ jobs:
             - name: Npm release
               continue-on-error: true
               id: publish_release
-              if: steps.check_version_npm.outputs.bump == 'true'
               run: |
                   if [[ "${{ vars.HOST_GITHUB_ACTIONS }}" == true ]]; then
                     echo "Running on GitHub Actions"
@@ -474,7 +233,6 @@ jobs:
             - name: Docker js_server release
               continue-on-error: true
               id: publish_docker_js_server
-              if: steps.check_version_docker_js_server.outputs.bump == 'true'
               run: |
                   # Push the new image to Docker Hub
                   echo "Pushing Docker image..."
@@ -537,15 +295,12 @@ jobs:
             # Add support for more platforms with QEMU (optional)
             # https://github.com/docker/setup-qemu-action
             - name: Set up QEMU
-              if: steps.check_version_docker_js_server.outputs.bump == 'true'
               uses: docker/setup-qemu-action@v3
 
             - name: Set up Docker Buildx
-              if: steps.check_version_docker_js_server.outputs.bump == 'true'
               uses: docker/setup-buildx-action@v3
 
             - name: Build the production CLI package
-              if: steps.check_version_docker_js_server.outputs.bump == 'true'
               run: |
                   echo "Building the production CLI package..."
                   # Copy the rococo env file to production env file
@@ -563,7 +318,6 @@ jobs:
                   cd ../..
 
             - name: Build and push the Provider Container
-              if: steps.check_version_docker_js_server.outputs.bump == 'true'
               id: publish_docker_provider
               continue-on-error: true
               uses: docker/build-push-action@v5
