rename publish to release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,12 +1,11 @@
-# Publish packages after a release
+# Publish + deploy packages after a release
 
-name: publish
+name: release
 
 on:
     push:
         # only on the main branch
-        branches:
-            - main
+        branches: [ release/* ]
 
 jobs:
     publish:
@@ -64,7 +63,19 @@ jobs:
               id: next_version
               run: |
 
-                  VERSION=$(cat package.json | jq -r '.version' || echo "0.0.0")
+                  VERSION=$(cat package.json | jq -r '.version')
+
+                  # if version not detected, error
+                    if [[ -z "$VERSION" ]]; then
+                        echo "Failed to get version"
+                        exit 1
+                    fi
+                    # or if version null
+                    if [[ "$VERSION" == "null" ]]; then
+                        echo "Failed to get version"
+                        exit 1
+                    fi
+
                   # split into major, minor, patch
                   MAJOR=$(echo $VERSION | cut -d. -f1)
                   MINOR=$(echo $VERSION | cut -d. -f2)
